#undef VCL_STRING_INSTANTIATE
#undef VCL_BASIC_STRING_INSTANTIATE

#define VCL_STRING_INSTANTIATE(T)
#undef VCL_BASIC_STRING_INSTANTIATE
#define VCL_BASIC_STRING_INSTANTIATE(charT, Traits) \
/* wibble */
