extern int v3p_netlib_zhgeqz_(
  char *job,
  char *compq,
  char *compz,
  v3p_netlib_integer *n,
  v3p_netlib_integer *ilo,
  v3p_netlib_integer *ihi,
  v3p_netlib_doublecomplex *h__,
  v3p_netlib_integer *ldh,
  v3p_netlib_doublecomplex *t,
  v3p_netlib_integer *ldt,
  v3p_netlib_doublecomplex *alpha,
  v3p_netlib_doublecomplex *beta,
  v3p_netlib_doublecomplex *q,
  v3p_netlib_integer *ldq,
  v3p_netlib_doublecomplex *z__,
  v3p_netlib_integer *ldz,
  v3p_netlib_doublecomplex *work,
  v3p_netlib_integer *lwork,
  v3p_netlib_doublereal *rwork,
  v3p_netlib_integer *info,
  v3p_netlib_ftnlen job_len,
  v3p_netlib_ftnlen compq_len,
  v3p_netlib_ftnlen compz_len
  );
