# Commit prefix regexes
type:Compiler:
  title: "^COMP:.*"

type:Bug:
  title: "^BUG:.*"

area:Documentation:
  title: "^DOC:.*"

type:Enhancement:
  title: "^ENH:.*"

type:Performance:
  title: "^PERF:.*"

type:Style:
  title: "^STYLE:.*"

# Modified filename regexes
area:Bridge:
  files:
    - "Modules/Bridge/*"

area:Core:
  files:
    - "Modules/Core/*"

area:Documentation:
  files:
    - "Documentation/*"

area:Examples:
  files:
    - "Examples/*"

area:Filtering:
  files:
    - "Modules/Filtering/*"

area:IO:
  files:
    - "Modules/IO/*"

area:Numerics:
  files:
    - "Modules/Numerics/*"

area:Python wrapping:
  files:
    - ".*.py*"

area:Registration:
  files:
    - "Modules/Registration/*"

area:Remotes:
  files:
    - "Modules/Remote/*"

area:Segmentation:
  files:
    - "Modules/Segmentation/*"

area:ThirdParty:
  files:
    - "Modules/ThirdParty/*"

area:Video:
  files:
    - "Modules/Video/*"

type:Testing:
  files:
    - "Testing/*"
    - ".*Test.*.cxx"
    - ".*Test.*.py"
