WRAP_CLASS("itk::DisplacementFieldJacobianDeterminantFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(v ${WRAP_ITK_VECTOR_REAL})
      FOREACH(r ${WRAP_ITK_REAL})
        WRAP_TEMPLATE("${ITKM_I${v}${d}${d}}${ITKM_${r}}" "${ITKT_I${v}${d}${d}}, ${ITKT_${r}}")
      ENDFOREACH(r)
    ENDFOREACH(v)
  ENDFOREACH(d)
END_WRAP_CLASS()
