set(CTEST_SITE "$ENV{NODE_NAME}.azure")
if(UNIX)
  set(PLATFORM "Linux")
  execute_process(COMMAND
    gcc -v 2>&1 | tail -1 | awk '{print $3}'
    OUTPUT_VARIABLE GCC_VERSION
    )
  set(COMPILER "gcc-$ENV{GCC_VERSION}")
  set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
  set(dashboard_data_name "/jenkins/data")
elseif(WIN32)
  set(PLATFORM "Windows")
  set(COMPILER "VS12")
  set(CTEST_CMAKE_GENERATOR "Visual Studio 12")
  set(dashboard_data_name "C:/Jenkins/data")
  include( ProcessorCount )
  ProcessorCount( PROCESSOR_COUNT )
  if(PROCESSOR_COUNT)
    set(CTEST_TEST_ARGS PARALLEL_LEVEL ${PROCESSOR_COUNT})
    set(ENV{CFLAGS} "/MP${PROCESSOR_COUNT}")
    set(ENV{CXXFLAGS} "/MP${PROCESSOR_COUNT}")
  endif()
else()
endif()
set(CTEST_BUILD_NAME "${PLATFORM}-${COMPILER}-$ENV{GERRIT_BRANCH_NAME}-$ENV{GERRIT_CHANGE_NUMBER}-$ENV{GERRIT_PATCHSET_NUMBER}")
set(CTEST_BUILD_CONFIGURATION Debug)
set(CTEST_DASHBOARD_ROOT "$ENV{WORKSPACE}/$ENV{GERRIT_CHANGE_NUMBER}-$ENV{GERRIT_PATCHSET_NUMBER}")
set(CTEST_SOURCE_DIRECTORY "ITK-src")
set(CTEST_BINARY_DIRECTORY "ITK-bin")
set(dashboard_model "Experimental")
set(dashboard_track "Gerrit")
set(dashboard_git_url "http://review.source.kitware.com/p/ITK")
set(dashboard_git_branch "$ENV{GERRIT_BRANCH_NAME}")

message("CTEST_SITE = ${CTEST_SITE}")
message("GCC_VERSION = $ENV{GCC_VERSION}")
message("CTEST_BUILD_NAME = ${CTEST_BUILD_NAME}")
include(${CTEST_SCRIPT_DIRECTORY}/itk_common.cmake)

