#
# This module add the ITK include paths to a project
# It should be included after the FindITK module
#
IF (ITK_BINARY_PATH)
  LOAD_CACHE(${ITK_BINARY_PATH} 
  EXCLUDE
    BUILD_SHARED_LIBS
    BUILD_TESTING
    BUILD_EXAMPLES
    LIBRARY_OUTPUT_PATH
    EXECUTABLE_OUTPUT_PATH
    MAKECOMMAND 
    SITE
    BUILDNAME
    CVS_UPDATE_OPTIONS
    DART_TESTING_TIMEOUT
    VTK_INSTALL_PATH
  INCLUDE_INTERNALS
    ITK_BINARY_DIR
    ITK_LIBRARY_PATH
    ITK_BUILD_SHARED_LIBS
    VTK_BINARY_DIR
    VTK_BUILD_SHARED_LIBS
    VTK_LIBRARY_PATH
    )
    INCLUDE (${ITK_SOURCE_DIR}/itkCMakeOptions.cmake)
    LINK_DIRECTORIES(${ITK_LIBRARY_PATH})
ENDIF (ITK_BINARY_PATH)

