WRAP_CLASS("itk::NearestNeighborInterpolateImageFunction" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_SCALAR})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
