WRAP_CLASS("itk::ScaleTransform" POINTER)
  foreach(d ${EXPLICIT_ITK_DIMS})
    WRAP_TEMPLATE("${ITKM_D}${d}" "${ITKT_D},${d}")
  endforeach(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::ScaleLogarithmicTransform" POINTER)
  foreach(d ${EXPLICIT_ITK_DIMS})
    WRAP_TEMPLATE("${ITKM_D}${d}" "${ITKT_D},${d}")
  endforeach(d)
END_WRAP_CLASS()
