WRAP_NON_TEMPLATE_CLASS("itk::TransformBase" POINTER)

WRAP_CLASS("itk::Transform" POINTER)
  foreach(d1 ${EXPLICIT_ITK_DIMS})
    foreach(d2 ${EXPLICIT_ITK_DIMS})
      if("${d1}" GREATER "${d2}" OR "${d1}" EQUAL "${d2}")
        WRAP_TEMPLATE("${ITKM_D}${d1}${d2}" "${ITKT_D},${d1},${d2}")
      endif("${d1}" GREATER "${d2}" OR "${d1}" EQUAL "${d2}")
    endforeach(d2)
  endforeach(d1)
END_WRAP_CLASS()
