/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    itkStatisticsHeaderTest.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) Insight Software Consortium. All rights reserved.
  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/

#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkChiSquareDistribution.h"
#include "itkGaussianDistribution.h"
#include "itkProbabilityDistribution.h"
#include "itkTDistribution.h"
#include "itkListSample.h"
#include "itkHistogram.h"
#include "itkSampleToHistogramFilter.h"
#include "itkHistogramToTextureFeaturesFilter.h"
#include "itkSample.h"
#include "itkSampleClassifierFilter.h"
#include "itkSampleToSubsampleFilter.h"
#include "itkSubsample.h"
#include "itkMeanSampleFilter.h"
#include "itkMembershipSample.h"
#include "itkNeighborhoodSampler.h"
#include "itkCovarianceSampleFilter.h"
#include "itkWeightedMeanSampleFilter.h"
#include "itkWeightedCovarianceSampleFilter.h"
#include "itkImageToListSampleFilter.h"
#include "itkScalarImageToCooccurrenceMatrixFilter.h"
#include "itkScalarImageToCooccurrenceListSampleFilter.h"
#include "itkImageToListSampleAdaptor.h"
#include "itkPointSetToListSampleAdaptor.h"
#include "itkJointDomainImageToListSampleAdaptor.h"
#include "itkScalarImageToTextureFeaturesFilter.h"
#include "itkMembershipFunctionBase.h"
#include "itkDistanceMetric.h"
#include "itkEuclideanDistanceMetric.h"
#include "itkEuclideanSquareDistanceMetric.h"
#include "itkMahalanobisDistanceMetric.h"
#include "itkManhattanDistanceMetric.h"
#include "itkDecisionRule.h"
#include "itkMaximumDecisionRule2.h"
#include "itkMaximumRatioDecisionRule2.h"
#include "itkMinimumDecisionRule2.h"
#include "itkDistanceToCentroidMembershipFunction.h"
#include "itkGaussianMembershipFunction.h"
#include "itkSampleClassifierFilter.h"
#include "itkExpectationMaximizationMixtureModelEstimator.h"
#include "itkKdTreeBasedKmeansEstimator.h"


int main ( int , char *[]  )
{
  return EXIT_SUCCESS;
}
