SET(ExplicitITK_SOURCE_DIR "${ITK_SOURCE_DIR}/Wrapping/ExplicitITK")

INCLUDE(${ExplicitITK_SOURCE_DIR}/CreateITKExplicitInstantiations.cmake)

BEGIN_WRAPPER_LIBRARY(ITKCommon "${ExplicitITK_SOURCE_DIR}/Modules/Common")

WRAPPER_LIBRARY_CREATE_EXPLICIT_INSTANTIATION_FILES("ITKCommon")
WRAPPER_LIBRARY_CREATE_EXPLICIT_INSTANTIATION_SOURCES()

