WRAP_CLASS("itk::ImportImageContainer")
WRAP_TEMPLATE("ULB" "unsigned long,bool")
WRAP_TEMPLATE("ULSC" "unsigned long,char")
WRAP_TEMPLATE("ULD" "unsigned long,double")
WRAP_TEMPLATE("ULF" "unsigned long,float")
WRAP_TEMPLATE("ULSI" "unsigned long,int")
WRAP_TEMPLATE("ULFAD3" "unsigned long,Templates::FixedArrayD3")
WRAP_TEMPLATE("ULFAF1" "unsigned long,Templates::FixedArrayF1")
WRAP_TEMPLATE("ULFAF2" "unsigned long,Templates::FixedArrayF2")
WRAP_TEMPLATE("ULFAF3" "unsigned long,Templates::FixedArrayF3")
WRAP_TEMPLATE("ULFAF6" "unsigned long,Templates::FixedArrayF6")
WRAP_TEMPLATE("ULFASI3" "unsigned long,Templates::FixedArraySI3")
WRAP_TEMPLATE("ULFAUC4" "unsigned long,Templates::FixedArrayUC4")
WRAP_TEMPLATE("ULPF2" "unsigned long,Templates::PointF2")
WRAP_TEMPLATE("ULVSC2" "unsigned long,Templates::VectorSC2")
WRAP_TEMPLATE("ULVSC4" "unsigned long,Templates::VectorSC4")
WRAP_TEMPLATE("ULVD2" "unsigned long,Templates::VectorD2")
WRAP_TEMPLATE("ULVD3" "unsigned long,Templates::VectorD3")
WRAP_TEMPLATE("ULVD4" "unsigned long,Templates::VectorD4")
WRAP_TEMPLATE("ULVF1" "unsigned long,Templates::VectorF1")
WRAP_TEMPLATE("ULVF2" "unsigned long,Templates::VectorF2")
WRAP_TEMPLATE("ULVF3" "unsigned long,Templates::VectorF3")
WRAP_TEMPLATE("ULVF4" "unsigned long,Templates::VectorF4")
WRAP_TEMPLATE("ULVF6" "unsigned long,Templates::VectorF6")
WRAP_TEMPLATE("ULVSI2" "unsigned long,Templates::VectorSI2")
WRAP_TEMPLATE("ULVSI3" "unsigned long,Templates::VectorSI3")
WRAP_TEMPLATE("ULVSI4" "unsigned long,Templates::VectorSI4")
WRAP_TEMPLATE("ULVSS1" "unsigned long,Templates::VectorSS1")
WRAP_TEMPLATE("ULVSS2" "unsigned long,Templates::VectorSS2")
WRAP_TEMPLATE("ULVSS4" "unsigned long,Templates::VectorSS4")
WRAP_TEMPLATE("ULVUC2" "unsigned long,Templates::VectorUC2")
WRAP_TEMPLATE("ULVUC3" "unsigned long,Templates::VectorUC3")
WRAP_TEMPLATE("ULVUC4" "unsigned long,Templates::VectorUC4")
WRAP_TEMPLATE("ULVUI4" "unsigned long,Templates::VectorUI4")
WRAP_TEMPLATE("ULVUS1" "unsigned long,Templates::VectorUS1")
WRAP_TEMPLATE("ULVUS2" "unsigned long,Templates::VectorUS2")
WRAP_TEMPLATE("ULVUS3" "unsigned long,Templates::VectorUS3")
WRAP_TEMPLATE("ULVUS4" "unsigned long,Templates::VectorUS4")
WRAP_TEMPLATE("ULVUS5" "unsigned long,Templates::VectorUS5")
WRAP_TEMPLATE("ULSL" "unsigned long,long")
WRAP_TEMPLATE("ULSS" "unsigned long,short")
WRAP_TEMPLATE("ULUC" "unsigned long,unsigned char")
WRAP_TEMPLATE("ULUI" "unsigned long,unsigned int")
WRAP_TEMPLATE("ULUL" "unsigned long,unsigned long")
WRAP_TEMPLATE("ULUS" "unsigned long,unsigned short")
WRAP_TEMPLATE("ULBCAP3" "unsigned long,Templates::BloxCoreAtomPixel3")
WRAP_TEMPLATE("ULBBPP3" "unsigned long,Templates::BloxBoundaryPointPixel3")
WRAP_TEMPLATE("ULBBPrP3" "unsigned long,Templates::BloxBoundaryProfilePixel3")
END_WRAP_CLASS()
