WRAP_CLASS("itk::VectorLinearInterpolateImageFunction")
WRAP_TEMPLATE("IFAF22F" "Templates::ImageFAF22,float")
WRAP_TEMPLATE("IFAF33F" "Templates::ImageFAF33,float")
WRAP_TEMPLATE("IVF22D" "Templates::ImageVF22,double")
WRAP_TEMPLATE("IVF22F" "Templates::ImageVF22,float")
WRAP_TEMPLATE("IVF32D" "Templates::ImageVF32,double")
WRAP_TEMPLATE("IVF33D" "Templates::ImageVF33,double")
WRAP_TEMPLATE("IVUS33D" "Templates::ImageVUS33,double")
END_WRAP_CLASS()
