WRAP_CLASS("itk::MapContainer")
WRAP_TEMPLATE("ULD" "unsigned long,double")
WRAP_TEMPLATE("ULF" "unsigned long,float")
WRAP_TEMPLATE("ULSI" "unsigned long,int")
WRAP_TEMPLATE("ULPD2" "unsigned long,Templates::PointD2")
WRAP_TEMPLATE("ULPD3" "unsigned long,Templates::PointD3")
WRAP_TEMPLATE("ULPD4" "unsigned long,Templates::PointD4")
WRAP_TEMPLATE("ULPF2" "unsigned long,Templates::PointF2")
WRAP_TEMPLATE("ULPF3" "unsigned long,Templates::PointF3")
WRAP_TEMPLATE("ULUL" "unsigned long,unsigned long")
END_WRAP_CLASS()
