WRAP_CLASS("itk::Vector")
WRAP_TEMPLATE("D1" "double,1")
WRAP_TEMPLATE("D2" "double,2")
WRAP_TEMPLATE("D3" "double,3")
WRAP_TEMPLATE("D4" "double,4")
WRAP_TEMPLATE("D5" "double,5")
WRAP_TEMPLATE("D6" "double,6")
WRAP_TEMPLATE("F1" "float,1")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("F4" "float,4")
WRAP_TEMPLATE("F6" "float,6")
WRAP_TEMPLATE("US1" "unsigned short,1")
WRAP_TEMPLATE("SC2" "char,2")
WRAP_TEMPLATE("SC4" "char,4")
WRAP_TEMPLATE("SI2" "int,2")
WRAP_TEMPLATE("SI3" "int,3")
WRAP_TEMPLATE("SI4" "int,4")
WRAP_TEMPLATE("SS1" "short,1")
WRAP_TEMPLATE("SS2" "short,2")
WRAP_TEMPLATE("SS4" "short,4")
WRAP_TEMPLATE("UC2" "unsigned char,2")
WRAP_TEMPLATE("UC3" "unsigned char,3")
WRAP_TEMPLATE("UC4" "unsigned char,4")
WRAP_TEMPLATE("UI4" "unsigned int,4")
WRAP_TEMPLATE("US2" "unsigned short,2")
WRAP_TEMPLATE("US3" "unsigned short,3")
WRAP_TEMPLATE("US4" "unsigned short,4")
WRAP_TEMPLATE("US5" "unsigned short,5")
WRAP_TEMPLATE("UI1" "unsigned int,1")
WRAP_TEMPLATE("UC1" "unsigned char,1")
END_WRAP_CLASS()
