WRAP_CLASS("itk::FiniteDifferenceFunction")
WRAP_TEMPLATE("IF2" "Templates::ImageF2")
WRAP_TEMPLATE("IF3" "Templates::ImageF3")
WRAP_TEMPLATE("IF4" "Templates::ImageF4")
WRAP_TEMPLATE("IVD22" "Templates::ImageVD22")
WRAP_TEMPLATE("IVF22" "Templates::ImageVF22")
WRAP_TEMPLATE("IVF32" "Templates::ImageVF32")
WRAP_TEMPLATE("IVF33" "Templates::ImageVF33")
END_WRAP_CLASS()
