WRAP_CLASS("itk::SimpleDataObjectDecorator")
WRAP_TEMPLATE("D" "double")
WRAP_TEMPLATE("F" "float")
WRAP_TEMPLATE("SI" "int")
WRAP_TEMPLATE("SS" "short")
WRAP_TEMPLATE("UC" "unsigned char")
WRAP_TEMPLATE("UL" "unsigned long")
WRAP_TEMPLATE("US" "unsigned short")
END_WRAP_CLASS()
