WRAP_CLASS("itk::DenseFiniteDifferenceImageFilter")
WRAP_TEMPLATE("IF2IF2" "Templates::ImageF2,Templates::ImageF2")
WRAP_TEMPLATE("IF3IF3" "Templates::ImageF3,Templates::ImageF3")
WRAP_TEMPLATE("IF4IF4" "Templates::ImageF4,Templates::ImageF4")
WRAP_TEMPLATE("IVF22IVF22" "Templates::ImageVF22,Templates::ImageVF22")
WRAP_TEMPLATE("IVF32IVF32" "Templates::ImageVF32,Templates::ImageVF32")
END_WRAP_CLASS()
