WRAP_CLASS("itk::MeanImageFunction")
WRAP_TEMPLATE("IF2D" "Templates::ImageF2,double")
WRAP_TEMPLATE("IF2F" "Templates::ImageF2,float")
WRAP_TEMPLATE("IUC3F" "Templates::ImageUC3,float")
END_WRAP_CLASS()
