WRAP_CLASS("itk::BinaryBallStructuringElement")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("SI2" "int,2")
WRAP_TEMPLATE("UC2" "unsigned char,2")
WRAP_TEMPLATE("UC3" "unsigned char,3")
WRAP_TEMPLATE("UI3" "unsigned int,3")
WRAP_TEMPLATE("US2" "unsigned short,2")
WRAP_TEMPLATE("US3" "unsigned short,3")
END_WRAP_CLASS()
