WRAP_CLASS("itk::LinearInterpolateImageFunction")
WRAP_TEMPLATE("ISC2D" "Templates::ImageSC2,double")
WRAP_TEMPLATE("ISC3D" "Templates::ImageSC3,double")
WRAP_TEMPLATE("ID2D" "Templates::ImageD2,double")
WRAP_TEMPLATE("IF2D" "Templates::ImageF2,double")
WRAP_TEMPLATE("IF2F" "Templates::ImageF2,float")
WRAP_TEMPLATE("IF3D" "Templates::ImageF3,double")
WRAP_TEMPLATE("IF3F" "Templates::ImageF3,float")
WRAP_TEMPLATE("ISI2D" "Templates::ImageSI2,double")
WRAP_TEMPLATE("ISL2D" "Templates::ImageSL2,double")
WRAP_TEMPLATE("ISS2D" "Templates::ImageSS2,double")
WRAP_TEMPLATE("IUC2D" "Templates::ImageUC2,double")
WRAP_TEMPLATE("IUC3D" "Templates::ImageUC3,double")
WRAP_TEMPLATE("IUI2D" "Templates::ImageUI2,double")
WRAP_TEMPLATE("IUL2D" "Templates::ImageUL2,double")
WRAP_TEMPLATE("IUL3F" "Templates::ImageUL3,float")
WRAP_TEMPLATE("IUS2D" "Templates::ImageUS2,double")
WRAP_TEMPLATE("IUS3D" "Templates::ImageUS3,double")
WRAP_TEMPLATE("IUS3F" "Templates::ImageUS3,float")
END_WRAP_CLASS()
