WRAP_CLASS("itk::ConditionalConstIterator")
WRAP_TEMPLATE("IB2" "Templates::ImageB2")
WRAP_TEMPLATE("IF2" "Templates::ImageF2")
WRAP_TEMPLATE("IF3" "Templates::ImageF3")
WRAP_TEMPLATE("ISI2" "Templates::ImageSI2")
WRAP_TEMPLATE("ISI3" "Templates::ImageSI3")
WRAP_TEMPLATE("IUC2" "Templates::ImageUC2")
WRAP_TEMPLATE("IUC3" "Templates::ImageUC3")
WRAP_TEMPLATE("IUI3" "Templates::ImageUI3")
WRAP_TEMPLATE("IUS2" "Templates::ImageUS2")
WRAP_TEMPLATE("IUS3" "Templates::ImageUS3")
WRAP_NO_INCLUDE("BCAI3")
WRAP_TEMPLATE("BCAI3" "Templates::BloxCoreAtomImage3")
END_WRAP_CLASS()
