WRAP_CLASS("itk::InteriorExteriorSpatialFunction")
WRAP_TEMPLATE("2PD2" "2,Templates::PointD2")
WRAP_TEMPLATE("2PF2" "2,Templates::PointF2")
WRAP_TEMPLATE("3PD3" "3,Templates::PointD3")
WRAP_TEMPLATE("3PF3" "3,Templates::PointF3")
END_WRAP_CLASS()
