WRAP_CLASS("itk::VectorContainer")
WRAP_TEMPLATE("UCD" "unsigned char,double")
WRAP_TEMPLATE("UID" "unsigned int,double")
WRAP_TEMPLATE("UIVD1" "unsigned int,Templates::VectorD1")
WRAP_TEMPLATE("UIVD2" "unsigned int,Templates::VectorD2")
WRAP_TEMPLATE("UIVF1" "unsigned int,Templates::VectorF1")
WRAP_TEMPLATE("UIVF2" "unsigned int,Templates::VectorF2")
WRAP_TEMPLATE("UIVUC1" "unsigned int,Templates::VectorUC1")
WRAP_TEMPLATE("ULD" "unsigned long,double")
WRAP_TEMPLATE("ULF" "unsigned long,float")
WRAP_TEMPLATE("ULSI" "unsigned long,int")
WRAP_TEMPLATE("ULPD1" "unsigned long,Templates::PointD1")
WRAP_TEMPLATE("ULPD2" "unsigned long,Templates::PointD2")
WRAP_TEMPLATE("ULPD3" "unsigned long,Templates::PointD3")
WRAP_TEMPLATE("ULPD4" "unsigned long,Templates::PointD4")
WRAP_TEMPLATE("ULPF2" "unsigned long,Templates::PointF2")
WRAP_TEMPLATE("ULPF3" "unsigned long,Templates::PointF3")
WRAP_TEMPLATE("ULVD2" "unsigned long,Templates::VectorD2")
WRAP_TEMPLATE("ULVD3" "unsigned long,Templates::VectorD3")
WRAP_TEMPLATE("ULVD4" "unsigned long,Templates::VectorD4")
WRAP_TEMPLATE("ULUL" "unsigned long,unsigned long")
WRAP_TEMPLATE("ULUS" "unsigned long,unsigned short")
END_WRAP_CLASS()
