WRAP_CLASS("itk::Transform")
WRAP_TEMPLATE("D22" "double,2,2")
WRAP_TEMPLATE("D32" "double,3,2")
WRAP_TEMPLATE("D33" "double,3,3")
WRAP_TEMPLATE("D44" "double,4,4")
WRAP_TEMPLATE("D66" "double,6,6")
WRAP_TEMPLATE("F33" "float,3,3")
END_WRAP_CLASS()
