WRAP_CLASS("itk::NeighborhoodInnerProduct")
WRAP_TEMPLATE("ID2DD" "Templates::ImageD2,double,double")
WRAP_TEMPLATE("IF2FF" "Templates::ImageF2,float,float")
WRAP_TEMPLATE("IF3FF" "Templates::ImageF3,float,float")
WRAP_TEMPLATE("IF2DD" "Templates::ImageF2,double,double")
END_WRAP_CLASS()
