WRAP_CLASS("itk::Neighborhood")
WRAP_TEMPLATE("B2" "bool,2")
WRAP_TEMPLATE("B3" "bool,3")
WRAP_TEMPLATE("D2" "double,2")
WRAP_TEMPLATE("D3" "double,3")
WRAP_TEMPLATE("D6" "double,6")
WRAP_TEMPLATE("Dp6" "double*,6")
WRAP_TEMPLATE("Dp2" "double*,2")
WRAP_TEMPLATE("Fp4" "float*,4")
WRAP_TEMPLATE("Fp3" "float*,3")
WRAP_TEMPLATE("Fp2" "float*,2")
WRAP_TEMPLATE("Sp2" "short*,2")
WRAP_TEMPLATE("UCp3" "unsigned char*,3")
WRAP_TEMPLATE("UCp2" "unsigned char*,2")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("F4" "float,4")
WRAP_TEMPLATE("SI2" "int,2")
WRAP_TEMPLATE("SI3" "int,3")
WRAP_NO_INCLUDE("VD22")
WRAP_NO_INCLUDE("VD23")
WRAP_NO_INCLUDE("VF22")
WRAP_NO_INCLUDE("VF32")
WRAP_NO_INCLUDE("VF33")
WRAP_NO_INCLUDE("VUS13")
WRAP_TEMPLATE("VD22" "Templates::VectorD2,2")
WRAP_TEMPLATE("VD23" "Templates::VectorD2,3")
WRAP_TEMPLATE("VF22" "Templates::VectorF2,2")
WRAP_TEMPLATE("VF32" "Templates::VectorF3,2")
WRAP_TEMPLATE("VF33" "Templates::VectorF3,3")
WRAP_TEMPLATE("VUS13" "Templates::VectorUS1,3")
WRAP_TEMPLATE("SL1" "long,1")
WRAP_TEMPLATE("SS2" "short,2")
WRAP_TEMPLATE("UC2" "unsigned char,2")
WRAP_TEMPLATE("UC3" "unsigned char,3")
WRAP_TEMPLATE("UI2" "unsigned int,2")
WRAP_TEMPLATE("UI3" "unsigned int,3")
WRAP_TEMPLATE("UL2" "unsigned long,2")
WRAP_TEMPLATE("US2" "unsigned short,2")
WRAP_TEMPLATE("US3" "unsigned short,3")
WRAP_TEMPLATE("FAUC43" "Templates::FixedArrayUC4,3")
END_WRAP_CLASS()
