WRAP_CLASS("itk::CentralDifferenceImageFunction")
WRAP_TEMPLATE("ID2F" "Templates::ImageD2,float")
WRAP_TEMPLATE("IF2D" "Templates::ImageF2,double")
WRAP_TEMPLATE("IF2F" "Templates::ImageF2,float")
WRAP_TEMPLATE("IF3D" "Templates::ImageF3,double")
WRAP_TEMPLATE("IUC2D" "Templates::ImageUC2,double")
WRAP_TEMPLATE("IUC2F" "Templates::ImageUC2,float")
WRAP_TEMPLATE("IUC3D" "Templates::ImageUC3,double")
WRAP_TEMPLATE("IUC3F" "Templates::ImageUC3,float")
WRAP_TEMPLATE("IUI2F" "Templates::ImageUI2,float")
END_WRAP_CLASS()
