WRAP_CLASS("itk::GaussianOperator")
WRAP_TEMPLATE("D2" "double,2")
WRAP_TEMPLATE("D3" "double,3")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("UC3" "unsigned char,3")
END_WRAP_CLASS()
