WRAP_CLASS("itk::Image")
WRAP_TEMPLATE("B2" "bool,2")
WRAP_TEMPLATE("B3" "bool,3")
WRAP_TEMPLATE("SC1" "char,1")
WRAP_TEMPLATE("SC2" "char,2")
WRAP_TEMPLATE("SC3" "char,3")
WRAP_TEMPLATE("SC4" "char,4")
WRAP_TEMPLATE("D1" "double,1")
WRAP_TEMPLATE("D2" "double,2")
WRAP_TEMPLATE("D3" "double,3")
WRAP_TEMPLATE("D4" "double,4")
WRAP_TEMPLATE("D6" "double,6")
WRAP_TEMPLATE("F1" "float,1")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("F4" "float,4")
WRAP_TEMPLATE("F5" "float,5")
WRAP_TEMPLATE("SI2" "int,2")
WRAP_TEMPLATE("SI3" "int,3")
WRAP_TEMPLATE("SI4" "int,4")
WRAP_TEMPLATE("FAD33" "Templates::FixedArrayD3,3")
WRAP_TEMPLATE("FAF13" "Templates::FixedArrayF1,3")
WRAP_TEMPLATE("FAF22" "Templates::FixedArrayF2,2")
WRAP_TEMPLATE("FAF23" "Templates::FixedArrayF2,3")
WRAP_TEMPLATE("FAF33" "Templates::FixedArrayF3,3")
WRAP_TEMPLATE("FAF63" "Templates::FixedArrayF6,3")
WRAP_TEMPLATE("FASI33" "Templates::FixedArraySI3,3")
WRAP_TEMPLATE("FAUC43" "Templates::FixedArrayUC4,3")
#WRAP_TEMPLATE("MUS222" "Templates::MatrixUS22,2")
WRAP_TEMPLATE("VSC22" "Templates::VectorSC2,2")
WRAP_TEMPLATE("VSC43" "Templates::VectorSC4,3")
WRAP_TEMPLATE("VD22" "Templates::VectorD2,2")
WRAP_TEMPLATE("VD23" "Templates::VectorD2,3")
WRAP_TEMPLATE("VD25" "Templates::VectorD2,5")
WRAP_TEMPLATE("VD31" "Templates::VectorD3,1")
WRAP_TEMPLATE("VD33" "Templates::VectorD3,3")
WRAP_TEMPLATE("VD42" "Templates::VectorD4,2")
WRAP_TEMPLATE("VD43" "Templates::VectorD4,3")
WRAP_TEMPLATE("VF14" "Templates::VectorF1,4")
WRAP_TEMPLATE("VF22" "Templates::VectorF2,2")
WRAP_TEMPLATE("VF23" "Templates::VectorF2,3")
WRAP_TEMPLATE("VF32" "Templates::VectorF3,2")
WRAP_TEMPLATE("VF33" "Templates::VectorF3,3")
WRAP_TEMPLATE("VF43" "Templates::VectorF4,3")
WRAP_TEMPLATE("VF62" "Templates::VectorF6,2")
WRAP_TEMPLATE("VF63" "Templates::VectorF6,3")
WRAP_TEMPLATE("VSI22" "Templates::VectorSI2,2")
WRAP_TEMPLATE("VSI32" "Templates::VectorSI3,2")
WRAP_TEMPLATE("VSI33" "Templates::VectorSI3,3")
WRAP_TEMPLATE("VSI43" "Templates::VectorSI4,3")
WRAP_TEMPLATE("VSS14" "Templates::VectorSS1,4")
WRAP_TEMPLATE("VSS23" "Templates::VectorSS2,3")
WRAP_TEMPLATE("VSS43" "Templates::VectorSS4,3")
WRAP_TEMPLATE("VUC23" "Templates::VectorUC2,3")
WRAP_TEMPLATE("VUC31" "Templates::VectorUC3,1")
WRAP_TEMPLATE("VUC33" "Templates::VectorUC3,3")
WRAP_TEMPLATE("VUC43" "Templates::VectorUC4,3")
WRAP_TEMPLATE("VUI43" "Templates::VectorUI4,3")
WRAP_TEMPLATE("VUS13" "Templates::VectorUS1,3")
WRAP_TEMPLATE("VUS22" "Templates::VectorUS2,2")
WRAP_TEMPLATE("VUS33" "Templates::VectorUS3,3")
WRAP_TEMPLATE("VUS42" "Templates::VectorUS4,2")
WRAP_TEMPLATE("VUS43" "Templates::VectorUS4,3")
WRAP_TEMPLATE("VUS53" "Templates::VectorUS5,3")
WRAP_TEMPLATE("SL1" "long,1")
WRAP_TEMPLATE("SL2" "long,2")
WRAP_TEMPLATE("SL3" "long,3")
WRAP_TEMPLATE("SS1" "short,1")
WRAP_TEMPLATE("SS2" "short,2")
WRAP_TEMPLATE("SS3" "short,3")
WRAP_TEMPLATE("SS4" "short,4")
WRAP_TEMPLATE("UC2" "unsigned char,2")
WRAP_TEMPLATE("UC3" "unsigned char,3")
WRAP_TEMPLATE("UC4" "unsigned char,4")
WRAP_TEMPLATE("UC6" "unsigned char,6")
WRAP_TEMPLATE("UI1" "unsigned int,1")
WRAP_TEMPLATE("UI2" "unsigned int,2")
WRAP_TEMPLATE("UI3" "unsigned int,3")
WRAP_TEMPLATE("UI4" "unsigned int,4")
WRAP_TEMPLATE("UL2" "unsigned long,2")
WRAP_TEMPLATE("UL3" "unsigned long,3")
WRAP_TEMPLATE("US2" "unsigned short,2")
WRAP_TEMPLATE("S2" "short,2")
WRAP_TEMPLATE("US3" "unsigned short,3")
WRAP_TEMPLATE("US4" "unsigned short,4")
WRAP_TEMPLATE("US5" "unsigned short,5")
WRAP_TEMPLATE("BCAP33" "Templates::BloxCoreAtomPixel3,3")
WRAP_TEMPLATE("BBPP33" "Templates::BloxBoundaryPointPixel3,3")
WRAP_TEMPLATE("BBPrP33" "Templates::BloxBoundaryProfilePixel3,3")
END_WRAP_CLASS()
