WRAP_CLASS("itk::DerivativeOperator")
WRAP_TEMPLATE("D2" "double,2")
WRAP_TEMPLATE("D3" "double,3")
WRAP_TEMPLATE("F2" "float,2")
WRAP_TEMPLATE("F3" "float,3")
WRAP_TEMPLATE("SS2" "short,2")
END_WRAP_CLASS()
