WRAP_INCLUDE("itkPolyLineParametricPath.h" POINTER)
WRAP_CLASS("itk::ImageToPathFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_SCALAR})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}PLPP${d}" "${ITKT_I${t}${d}}, itk::PolyLineParametricPath< ${d} >")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
