/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:    itkCommonHeaderTest.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkAffineRegistrationTransform.h"
#include "itkAffineTransform.h"
#include "itkArray.h"
#include "itkBackwardDifferenceOperator.h"
#include "itkBlueDataAccessor.h"
#include "itkBoundingBox.h"
#include "itkByteSwapper.h"
#include "itkCellBoundary.h"
#include "itkCellInterface.h"
#include "itkCellInterfaceVisitor.h"
#include "itkCommand.h"
#include "itkCovariantVector.h"
#include "itkCreateObjectFunction.h"
#include "itkDataAccessor.h"
#include "itkDataObject.h"
#include "itkDefaultDynamicMeshType.h"
#include "itkDefaultStaticMeshType.h"
#include "itkDerivativeOperator.h"
#include "itkDirectory.h"
#include "itkDynamicLoader.h"
#include "itkEntropyPreservingGradientMagnitudeImageFunction.h"
#include "itkExceptionObject.h"
#include "itkFastMutexLock.h"
#include "itkForwardDifferenceOperator.h"
#include "itkGaussianOperator.h"
#include "itkGreenDataAccessor.h"
#include "itkHexahedronCell.h"
#include "itkImage.h"
#include "itkImageAdaptor.h"
#include "itkImageBase.h"
#include "itkImageBufferIterator.h"
#include "itkImageContainerInterface.h"
#include "itkImageFunction.h"
#include "itkImageIO.h"
#include "itkImageIOCommon.h"
#include "itkImageIterator.h"
#include "itkImageIteratorWithIndex.h"
#include "itkImageLinearIterator.h"
#include "itkImageRegion.h"
#include "itkImageRegionIterator.h"
#include "itkImageSliceIterator.h"
#include "itkImageSource.h"
#include "itkImageToImageFilter.h"
#include "itkImportImageContainer.h"
#include "itkIndent.h"
#include "itkIndex.h"
#include "itkIndexedContainerInterface.h"
#include "itkIntTypes.h"
#include "itkLevelSetCurvatureFunction.h"
#include "itkLightObject.h"
#include "itkLineCell.h"
#include "itkLinearInterpolateImageFunction.h"
#include "itkMacro.h"
#include "itkMapContainer.h"
#include "itkMesh.h"
#include "itkMeshRegion.h"
#include "itkMultiThreader.h"
#include "itkMutexLock.h"
#include "itkNeighborhood.h"
#include "itkNeighborhoodAlgorithm.h"
#include "itkNeighborhoodBase.h"
#include "itkNeighborhoodIterator.h"
#include "itkNeighborhoodOperator.h"
#include "itkNew.h"
#include "itkNumericTraits.h"
#include "itkObject.h"
#include "itkObjectFactory.h"
#include "itkObjectFactoryBase.h"
#include "itkOutputWindow.h"
#include "itkPixelTraits.h"
#include "itkPoint.h"
#include "itkPointLocator.h"
#include "itkProcessObject.h"
#include "itkQuadrilateralCell.h"
#include "itkRGBPixel.h"
#include "itkRandomAccessNeighborhoodIterator.h"
#include "itkRedDataAccessor.h"
#include "itkRegion.h"
#include "itkRegionBoundaryNeighborhoodIterator.h"
#include "itkRegionNeighborhoodIterator.h"
#include "itkRegionNonBoundaryNeighborhoodIterator.h"
#include "itkScalar.h"
#include "itkScalarImageRegionIterator.h"
#include "itkScalarVector.h"
#include "itkSimpleImageRegionIterator.h"
#include "itkSize.h"
#include "itkSliceIterator.h"
#include "itkSmartPointer.h"
#include "itkSmartPointerForwardReference.h"
#include "itkSmartRegionNeighborhoodIterator.h"
#include "itkTetrahedronCell.h"
#include "itkTimeStamp.h"
#include "itkTransform.h"
#include "itkTriangleCell.h"
#include "itkUpwindDerivativeImageFunction.h"
#include "itkValarrayImageContainer.h"
#include "itkVector.h"
#include "itkVectorContainer.h"
#include "itkVersion.h"
#include "itkVertexCell.h"
#include "itkWin32Header.h"
#include "itkWin32OutputWindow.h"

int main ( int argc, char* argv )
{
  
  return 0;
}

