/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:    itkHeaderTest.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#include <iostream>


// Can't do this, has static member of a templated class
// #include "itkMaker.h"
// #include "itkFilterFileIOToImage.h"
// #include "itkFileIO.h"
// #include "itkFileIOCommon.h"

// Missing itkKalmanFilter.h
// #include "itkRegistrator3D2D.h"
// #include "itkRegistrator3D2DBatch.h"
// #include "itkRegistrator3D2DRecursive.h"
// #include "itkKalmanLinearEstimator.h"

#include "itkAffineMutualInformation.h"
#include "itkAffineMutualInformationVW.h"
#include "itkAffineTransform.h"
#include "itkBoundingBox.h"
#include "itkByteSwap.h"
#include "itkCellBoundary.h"
#include "itkCellInterface.h"
#include "itkCellInterfaceVisitor.h"
#include "itkClassifier.h"
#include "itkCommand.h"
#include "itkCreateObjectFunction.h"
#include "itkCurvatureFlow.h"
#include "itkDataAccessor.h"
#include "itkDataObject.h"
#include "itkDerivativeHalfBackwardOperator.h"
#include "itkDerivativeHalfForwardOperator.h"
#include "itkDerivativeOperator.h"
#include "itkDirectory.h"
#include "itkDynamicLoader.h"
#include "itkEntropyDerivativeFunction.h"
#include "itkEvolveLevelSet.h"
#include "itkExceptionObject.h"
#include "itkExtensionVelocities.h"
#include "itkExtractMeshConnectedRegions.h"
#include "itkFastMarchExtension.h"
#include "itkFastMarching.h"
#include "itkFastMutexLock.h"
#include "itkFilterImageAdd.h"
#include "itkFilterImageAnisotropicDiffusionBase.h"
#include "itkFilterImageAnisotropicDiffusion.h"
#include "itkFilterImageBinary.h"
#include "itkFilterImageDerivative.h"
#include "itkFilterImageDiscreteGaussian.h"
#include "itkFilterImageGradientMagnitude.h"
#include "itkFilterImageMult.h"
#include "itkFilterImageRecursiveGaussianFirstDerivative.h"
#include "itkFilterImageRecursiveGaussian.h"
#include "itkFilterImageRecursiveGaussianSecondDerivative.h"
#include "itkFilterImageSingleOperator.h"
#include "itkFilterImageSub.h"
#include "itkFilterImageTernaryAdd.h"
#include "itkFilterImageTernary.h"
#include "itkFilterImageTernaryModulus.h"
#include "itkFilterImageTernaryModulusSquare.h"
#include "itkFilterImageToImage.h"
#include "itkFilterImageVectorValuedAnisotropicDiffusion.h"
#include "itkFilterImageWatershedLevelAdaptor.h"
#include "itkFilterImageWatershedSegment.h"
#include "itkFilterMeshToMesh.h"
#include "itkGaussianOperator.h"
#include "itkGaussianSupervisedClassifier.h"
#include "itkGeodesicActiveContours.h"
#include "itkHexahedronCell.h"
#include "itkImageAdaptor.h"
#include "itkImageBase.h"
#include "itkImageBufferIterator.h"
#include "itkImageContainerInterface.h"
#include "itkImageFunction.h"
#include "itkImage.h"
#include "itkImageIterator.h"
#include "itkImageIteratorWithIndex.h"
#include "itkImageLinearIterator.h"
#include "itkImageMoments.h"
#include "itkImageRegion.h"
#include "itkImageRegionIterator.h"
#include "itkImageRegionSimpleIterator.h"
#include "itkImageScalarRegionIterator.h"
#include "itkImageSliceIterator.h"
#include "itkImageSource.h"
#include "itkImportImageContainer.h"
#include "itkImportImage.h"
#include "itkIndent.h"
#include "itkIndexedContainerInterface.h"
#include "itkIndex.h"
#include "itkIntTypes.h"
#include "itkKernelFunction.h"
#include "itkKMeansUnsupervisedClassifier.h"
#include "itkLevelSetCurvatureFunction.h"
#include "itkLevelSet.h"
#include "itkLevelSetShapeDetection.h"
#include "itkLightObject.h"
#include "itkLinearInterpolateFunction.h"
#include "itkLineCell.h"
#include "itkLocateLevelSetExtension.h"
#include "itkLocateLevelSet.h"
#include "itkMacro.h"
#include "itkMapContainer.h"
#include "itkMesh.h"
#include "itkMeshRegion.h"
#include "itkMeshSource.h"
#include "itkMeshTypeDefaultDynamic.h"
#include "itkMeshTypeDefault.h"
#include "itkMRFLabeller.h"
#include "itkMultiThreader.h"
#include "itkMutexLock.h"
#include "itkMutualInformation.h"
#include "itkMutualInformationRigidRegistration.h"
#include "itkMutualInformationRigidRegistrationVW.h"
#include "itkNeighborhoodAlgorithm.h"
#include "itkNeighborhoodBase.h"
#include "itkNeighborhood.h"
#include "itkNeighborhoodIterator.h"
#include "itkNeighborhoodOperator.h"
#include "itkNonThreadedShrinkImage.h"
#include "itkNullImageToImageFilterDriver.h"
#include "itkNumericTraits.h"
#include "itkObjectFactoryBase.h"
#include "itkObjectFactory.h"
#include "itkObject.h"
#include "itkOutputWindow.h"
#include "itkPixelTraits.h"
#include "itkPoint.h"
#include "itkPointLocator.h"
#include "itkProcessObject.h"
#include "itkQuadrilateralCell.h"
#include "itkRandomAccessNeighborhoodIterator.h"
#include "itkRandomImageSource.h"
#include "itkReadVTKImage.h"
#include "itkRegionBoundaryNeighborhoodIterator.h"
#include "itkRegionGrow.h"
#include "itkRegionGrowKLM.h"
#include "itkRegion.h"
#include "itkRegionNeighborhoodIterator.h"
#include "itkRegistrationMapper.h"
#include "itkRegistrationMapperImage.h"
#include "itkRegistrationMapperProcrustes.h"
#include "itkRegistrationMethod.h"
#include "itkRegistrationMetric.h"
#include "itkRegistrationMetricProcrustes.h"
#include "itkRegistrationOptimizerAmoeba.h"
#include "itkRegistrationOptimizerConjugateGradient.h"
#include "itkRegistrationOptimizer.h"
#include "itkRegistrationOptimizerLBFGS.h"
#include "itkRegistrationOptimizerLevenbergMarquardt.h"
#include "itkRegistrationOptimizerNonLinear.h"
#include "itkRegistrationTransformationAffine.h"
#include "itkRegistrationTransformation.h"
#include "itkReinitializeLevelSet.h"
#include "itkRGB.h"
#include "itkRGBorder.h"
#include "itkRGBorderKLM.h"
#include "itkRGRegion.h"
#include "itkRGRegionKLM.h"
#include "itkScalar.h"
#include "itkScalarVector.h"
#include "itkShrinkImage.h"
#include "itkSize.h"
#include "itkSliceIterator.h"
#include "itkSmartPointer.h"
#include "itkSmartRegionNeighborhoodIterator.h"
#include "itkSupervisedClassifier.h"
#include "itkTetrahedronCell.h"
#include "itkTimeStamp.h"
#include "itkTriangleCell.h"
#include "itkUnsupervisedClassifier.h"
#include "itkUpwindDerivativeFunction.h"
#include "itkValarrayImageContainer.h"
#include "itkVectorComponentDataAccessor.h"
#include "itkVectorContainer.h"
#include "itkVector.h"
#include "itkVersion.h"
#include "itkVertexCell.h"
#include "itkWriteImage.h"
#include "itkWriteRawImage.h"
#include "itkWriter.h"
#include "itkWriteVTKImage.h"
#include "vxl_copyright.h"


int main ( int argc, char* argv[] )
{
  
  return 0;
}
