###############################################################
#
#    Program:   Insight Segmentation & Registration Toolkit
#   
#    Copyright (c) 2000 National Library of Medicine
#    All rights reserved.
#
#    See COPYRIGHT.txt for copyright details.
#
#############################################################


VPATH = $(INSIGHT_HOME)/Code/Common

RESULT = $(HOME_LIB)/libInsight.a



#################################################
#
#	Suffixes used 
#
#################################################

.SUFFIXES: .o .cxx .h


#################################################
#
#	Include Directories
#
#################################################

INCLUDES = -I.  -I$(INSIGHT_HOME)/Code/Common -I$(INSIGHT_HOME)/Code/Insight3DParty/vxl


#################################################
#
#	Compiler Options
#
#################################################

COPTIONS =   -Wall        \
             -O3          \
             -DVCL_USE_NATIVE_STL \
             -fguiding-decls

COMPOPTIONS =   $(COPTIONS)   



################################################
#
#	Implicit Rules
#
################################################

.cxx.o:
	$(CXX) -c  $<   $(INCLUDES) $(COMPOPTIONS)


################################################
#
#	Object Files
#
################################################

OBJS =	itkObject.o \
        itkObjectFactoryBase.o \
        itkOutputWindow.o \
        itkProcessObject.o \
        itkRegistrator3D2D.o \
        itkRegistrator3D2DBatch.o \
        itkRegistrator3D2DRecursive.o \
        itkTimeStamp.o \
        itkVersion.o \
        itkWriter.o \
        itkMeshBase.o \
        itkIndent.o \
        itkImageBase.o \
        itkExceptionObject.o \
        itkDynamicLoader.o \
        itkDirectory.o \
        itkDataObject.o 

#        itkWin32OutputWindow.o \

#####################################################
#
#   The following Classes are templated
#   This is just a reference to keep track of them
#
#   itkPixelTraits.h
#   itkRandomImageSource.h
#   itkReadVTKImage.h
#   itkScalar.h
#   itkScalarVector.h
#   itkShrinkImage.h
#   itkSmartPointer.h
#   itkVector.h
#   itkWriteImage.h
#   itkWriteVTKImage.h
#   itkNumericTraits.h
#   itkMesh.h
#   itkKalmanFilter.h
#   itkIndex.h
#   itkImageSource.h
#   itkImageScalarIterator.h
#   itkImageIterator.h
#   itkImageIteratorPlain.h
#   itkImageIteratorOriented.h
#   itkImage.h
#   itkFilterImageToImage.h
#   itkFilterGaussian.h
#   itkFilterGaussianFirstDerivative.h
#   itkFilterGaussianSecondDerivative.h
#   itkCreateObjectFunction.h
#
#
#####################################################




#######################################################
#
#	Main target : create the library
#
#######################################################

all:	$(RESULT)



#######################################################
#
#	Remove all targets
#
#######################################################

clean: 
	rm *.o
	rm $(RESULT)





########################################################
#
#	Librarian commands
#
########################################################

$(RESULT):	$(OBJS)
	ar -uvr $(RESULT)  $(OBJS) 


