#!/usr/bin/env bash

# Alias to checkout a pull request by its numerical id
git config alias.pr "!bash Utilities/GitSetup/git-pr"
# Remove previously checked out pull request
git config alias.pr-clean '!git checkout master ; git for-each-ref refs/heads/pr/* --format="%(refname)" | while read ref ; do branch=${ref#refs/heads/} ; git branch -D $branch ; done'

# Alias to push the current topic branch to GitHub
git config alias.review-push "!bash Utilities/GitSetup/git-review-push"

git config alias.gerrit-push \
  "!bash -c 'echo \\\"git gerrit-push\\\" is deprecated. Please use \\\"git review-push\\\" instead.'"

# Useful alias to see what commits are on the current branch with respect to
# upstream/master
git config alias.prepush 'log --graph --stat upstream/master..'

# Alias to the script to upload testing data
git config alias.data-upload "!bash Utilities/UploadBinaryData.sh"
