IF(LIBRARY_OUTPUT_PATH)
  SET(CABLE_TCL_FACILITY_DIR ${LIBRARY_OUTPUT_PATH})
  SET(ITK_WRAP_TCL_DIR ${LIBRARY_OUTPUT_PATH})
  SET(ITK_WRAP_TCL_SUBDIRS "")
ELSE(LIBRARY_OUTPUT_PATH)
  SET(CABLE_TCL_FACILITY_DIR ${ITK_BINARY_DIR}/Utilities/Cable/WrapTclFacility)
  SET(ITK_WRAP_TCL_DIR ${ITK_BINARY_DIR}/Wrapping/Tcl)
  SET(ITK_WRAP_TCL_SUBDIRS "Common")
ENDIF(LIBRARY_OUTPUT_PATH)

SET(ITK_TCL_UTILS_DIR ${ITK_SOURCE_DIR}/Wrapping/Tcl)

CONFIGURE_FILE(${ITK_SOURCE_DIR}/Wrapping/Tcl/pkgIndex.tcl.in
               ${ITK_BINARY_DIR}/Wrapping/Tcl/pkgIndex.tcl)
