extern int v3p_netlib_dgges_(
  char v3p_netlib_const *jobvsl,
  char v3p_netlib_const *jobvsr,
  char v3p_netlib_const *sort,
  v3p_netlib_logical (*delctg)(v3p_netlib_doublereal*,
                               v3p_netlib_doublereal*,
                               v3p_netlib_doublereal*),
  v3p_netlib_integer *n,
  v3p_netlib_doublereal *a,
  v3p_netlib_integer *lda,
  v3p_netlib_doublereal *b,
  v3p_netlib_integer *ldb,
  v3p_netlib_integer *sdim,
  v3p_netlib_doublereal *alphar,
  v3p_netlib_doublereal *alphai,
  v3p_netlib_doublereal *beta,
  v3p_netlib_doublereal *vsl,
  v3p_netlib_integer *ldvsl,
  v3p_netlib_doublereal *vsr,
  v3p_netlib_integer *ldvsr,
  v3p_netlib_doublereal *work,
  v3p_netlib_integer *lwork,
  v3p_netlib_logical *bwork,
  v3p_netlib_integer *info,
  v3p_netlib_ftnlen jobvsl_len,
  v3p_netlib_ftnlen jobvsr_len,
  v3p_netlib_ftnlen sort_len
  );
