WRAP_CLASS("itk::BayesianClassifierInitializationImageFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_SCALAR})
      foreach(t3 ${WRAP_ITK_REAL})
        WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_${t3}}" "${ITKT_I${t}${d}}, ${ITKT_${t3}}")
      endforeach(t3)
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
