WRAP_CLASS("itk::BayesianClassifierImageFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_SCALAR})
      foreach(t2 ${WRAP_ITK_INT})
        foreach(t3 ${WRAP_ITK_REAL})
          WRAP_TEMPLATE("${ITKM_VI${t}${d}}${ITKM_${t2}}${ITKM_${t3}}${ITKM_${t3}}" "${ITKT_VI${t}${d}}, ${ITKT_${t2}}, ${ITKT_${t3}}, ${ITKT_${t3}}")
        endforeach(t3)
      endforeach(t2)
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
