WRAP_INCLUDE("itkPolyLineParametricPath.h" POINTER)
WRAP_CLASS("itk::ImageToPathFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}PLPP${d}" "${ITKT_I${t}${d}}, itk::PolyLineParametricPath< ${d} >")
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
