WRAP_CLASS("itk::MaskedRankImageFilter" POINTER_WITH_SUPERCLASS)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      FOREACH(l ${WRAP_ITK_INT})
        WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_I${l}${d}}${ITKM_I${t}${d}}${ITKM_SE${d}}"    "${ITKT_I${t}${d}},${ITKT_I${l}${d}},${ITKT_I${t}${d}},${ITKT_SE${d}}")
      ENDFOREACH(l)
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
