#include <vnl/algo/vnl_svd_fixed.hxx>
VNL_SVD_FIXED_INSTANTIATE(double, 1, 1);
VNL_SVD_FIXED_INSTANTIATE(double, 2, 2);
VNL_SVD_FIXED_INSTANTIATE(double, 2, 3);
VNL_SVD_FIXED_INSTANTIATE(double, 3, 2);
VNL_SVD_FIXED_INSTANTIATE(double, 3, 3);
VNL_SVD_FIXED_INSTANTIATE(double, 3, 4);
VNL_SVD_FIXED_INSTANTIATE(double, 4, 3);
VNL_SVD_FIXED_INSTANTIATE(double, 4, 4);
VNL_SVD_FIXED_INSTANTIATE(double, 5, 5);
VNL_SVD_FIXED_INSTANTIATE(double, 6, 6);
VNL_SVD_FIXED_INSTANTIATE(double, 7, 7);
VNL_SVD_FIXED_INSTANTIATE(double, 8, 8);
VNL_SVD_FIXED_INSTANTIATE(double, 9, 9);
VNL_SVD_FIXED_INSTANTIATE(double, 10, 10);
