/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:
  Language:  C++
  Date:
  Version:


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkAnalyzeDbh.h"
#include "itkAnalyzeImageIO.h"
#include "itkAnalyzeImageIOFactory.h"
#include "itkBioRadImageIO.h"
#include "itkBioRadImageIOFactory.h"
#include "itkBMPImageIO.h"
#include "itkBMPImageIOFactory.h"
#include "itkBrains2HeaderBase.h"
#include "itkBrains2HeaderFactory.h"
#include "itkBrains2IPLHeaderInfo.h"
#include "itkBrains2MaskHeaderInfo.h"
#include "itkBrains2MaskImageIO.h"
#include "itkBrains2MaskImageIOFactory.h"
#include "itkConvertPixelBuffer.txx"
#include "itkDICOMImageIO2.h"
#include "itkDICOMImageIO2Factory.h"
#include "itkDICOMSeriesFileNames.h"
#include "itkDefaultConvertPixelTraits.h"
#include "itkDicomImageIO.h"
#include "itkDicomImageIOFactory.h"
#include "itkGE4ImageIO.h"
#include "itkGE4ImageIOFactory.h"
#include "itkGE5ImageIO.h"
#include "itkGE5ImageIOFactory.h"
#include "itkGEAdwImageIO.h"
#include "itkGEAdwImageIOFactory.h"
#include "itkGEImageHeader.h"
#include "itkGiplImageIO.h"
#include "itkGiplImageIOFactory.h"
#include "itkIOCommon.h"
#include "itkIPLCommonImageIO.h"
#include "itkIPLFileNameList.h"
#include "itkImageFileReader.txx"
#include "itkImageFileWriter.txx"
#include "itkImageIOBase.h"
#include "itkImageIOFactory.h"
#include "itkImageIORegion.h"
#include "itkImageSeriesReader.txx"
#include "itkImageSeriesWriter.txx"
#include "itkJPEGImageIO.h"
#include "itkJPEGImageIOFactory.h"
#include "itkLSMImageIO.h"
#include "itkLSMImageIOFactory.h"
#include "itkMetaImageIO.h"
#include "itkMetaImageIOFactory.h"
#include "itkMvtSunf.h"
#include "itkNrrdImageIO.h"
#include "itkNrrdImageIOFactory.h"
#include "itkNumericSeriesFileNames.h"
#include "itkPNGImageIO.h"
#include "itkPNGImageIOFactory.h"
#include "itkPixelData.h"
#include "itkPolygonGroupSpatialObjectXMLFile.h"
#include "itkRawImageIO.txx"
#include "itkRegularExpressionSeriesFileNames.h"
#include "itkSiemensVisionImageIO.h"
#include "itkSiemensVisionImageIOFactory.h"
#include "itkSpatialObjectReader.txx"
#include "itkSpatialObjectWriter.txx"
#include "itkStimulateImageIO.h"
#include "itkStimulateImageIOFactory.h"
#include "itkTIFFImageIO.h"
#include "itkTIFFImageIOFactory.h"
#include "itkVTKImageIO.h"
#include "itkVTKImageIOFactory.h"
#include "itkXMLFile.h"

int main ( int , char*  )
{
  
  return EXIT_SUCCESS;
}

