/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:
  Language:  C++
  Date:
  Version:


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkConvertPixelBuffer.txx"
#include "itkDefaultConvertPixelTraits.h"
#include "itkDicomImageIO.h"
#include "itkDicomImageIOFactory.h"
#include "itkGiplImageIO.h"
#include "itkGiplImageIOFactory.h"
#include "itkImageFileReader.txx"
#include "itkImageFileWriter.txx"
#include "itkImageIOBase.h"
#include "itkImageIOFactory.h"
#include "itkImageIORegion.h"
#include "itkImageViewer.txx"
#include "itkImageViewerWindow.h"
#include "itkImageWriter.txx"
#include "itkMetaImageIO.h"
#include "itkMetaImageIOFactory.h"
#include "itkPNGImageIO.h"
#include "itkPNGImageIOFactory.h"
#include "itkRawImageIO.txx"
#include "itkRawImageWriter.txx"
#include "itkVOLImageIO.h"
#include "itkVOLImageIOFactory.h"
#include "itkVTKImageIO.h"
#include "itkVTKImageIOFactory.h"
#include "itkWriter.h"

int main ( int , char*  )
{
  
  return 0;
}

