#!/usr/bin/env python3
# ==========================================================================
#
#   Copyright NumFOCUS
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          https://www.apache.org/licenses/LICENSE-2.0.txt
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ==========================================================================
"""Generate the remote-module discoverability page for the ITK documentation.

Two sources are merged:

1. ``Modules/Remote/*.remote.cmake`` -- the authoritative set of remote
   modules that ITK can fetch and build. Name, description, compliance level,
   repository, and pinned tag are parsed directly from each ``itk_fetch_module``
   call.
2. ``Documentation/remote_modules_classification.yaml`` -- curated entries for
   repositories that are *not* in-tree remotes (itk-friends, forks, modules that
   have been integrated into ITK proper, non-C++ repositories, ...), plus the
   presentation metadata (compliance-level descriptions and section ordering)
   shared by every consumer of this data.

The script is deterministic and offline: it reads only the repository, so the
generated page can be committed and regenerated in CI without network access.
"""

import argparse
import re
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover - environment guard
    raise SystemExit(
        "GenerateRemoteModuleList.py requires PyYAML; install it with "
        "'python -m pip install pyyaml'."
    ) from exc


def _extract_first_call(text, func="itk_fetch_module"):
    """Return the argument text of the first balanced ``func(...)`` call."""
    start = text.find(func)
    if start == -1:
        return None
    open_paren = text.find("(", start)
    if open_paren == -1:
        return None
    depth = 0
    in_string = False
    for i in range(open_paren, len(text)):
        char = text[i]
        if in_string:
            if char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return text[open_paren + 1 : i]
    return None


def _normalize_repo(url):
    return re.sub(r"\.git$", "", url.strip().rstrip("/")) if url else ""


def _repo_link(repo):
    """Markdown link with concise text: ``owner/name`` for GitHub, else basename."""
    if not repo:
        return "-"
    if "github.com/" in repo:
        label = repo.split("github.com/", 1)[-1]
    else:
        label = repo.rstrip("/").split("/")[-1] or repo
    return f"[{label}]({repo})"


def parse_remote_cmake(path):
    """Return a dict of fields parsed from one ``*.remote.cmake`` file."""
    text = path.read_text(encoding="utf-8")
    # Anchor at the call so the leading "#-- ..." grading-report comment block is
    # skipped without stripping "#" lines that may live inside the quoted
    # description.
    inner = _extract_first_call(text)
    if inner is None:
        return None
    name = re.match(r"\s*([A-Za-z0-9_]+)", inner)
    description = re.search(r'"(.*?)"', inner, re.DOTALL)
    level = re.search(r"MODULE_COMPLIANCE_LEVEL\s+(\d+)", inner)
    repository = re.search(r"GIT_REPOSITORY\s+(\S+)", inner)
    return {
        "name": name.group(1) if name else path.stem.replace(".remote", ""),
        "description": " ".join(description.group(1).split()) if description else "",
        "level": level.group(1) if level else "",
        "repository": _normalize_repo(repository.group(1)) if repository else "",
    }


def load_in_tree(remote_dir):
    modules = []
    for path in sorted(remote_dir.glob("*.remote.cmake")):
        parsed = parse_remote_cmake(path)
        if parsed:
            modules.append(parsed)
    return modules


def load_data(path):
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _cell(text):
    """Escape Markdown table metacharacters so free text cannot break a row."""
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def _table(header, rows):
    out = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    out.extend("| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows)
    return "\n".join(out)


def render(in_tree, classified, compliance, kind_sections, command):
    lines = [
        "# ITK remote modules",
        "",
        "<!-- This page is generated by "
        f"`{command}`. Do not edit manually; edit the source "
        "(`Modules/Remote/*.remote.cmake` or "
        "`Documentation/remote_modules_classification.yaml`) and regenerate. -->",
        "",
        "Remote modules extend ITK with additional functionality maintained in "
        "separate repositories. The modules below can be enabled at configure "
        "time with `Module_<Name>`; see "
        "[the module workflow guide](../contributing/module_workflows.md).",
        "",
        "## Modules/Remote modules",
        "",
        "These remote modules ship a `*.remote.cmake` file in ITK and are "
        "fetched and built on demand. The compliance level reflects code "
        "maturity (5 = highest).",
        "",
    ]
    rows = []
    for m in sorted(in_tree, key=lambda m: m["name"].lower()):
        level = m["level"]
        level_text = f"{level} ({compliance.get(level, '')})" if level else "-"
        rows.append(
            [
                f"**{m['name']}**",
                level_text,
                _repo_link(m["repository"]),
                m["description"] or "-",
            ]
        )
    lines.append(
        _table(["Module", "Compliance level", "Repository", "Description"], rows)
    )
    lines.append("")

    known_kinds = {kind for kind, _, _ in kind_sections}
    by_kind = {}
    for entry in classified:
        kind = entry.get("kind", "candidate")
        if kind not in known_kinds:
            raise SystemExit(
                f"Unknown classification kind {kind!r} for {entry.get('name', entry.get('repo', '?'))}; "
                f"use one of {sorted(known_kinds)} or add it to the 'kinds' list."
            )
        by_kind.setdefault(kind, []).append(entry)

    for kind, heading, blurb in kind_sections:
        entries = by_kind.get(kind)
        if not entries:
            continue
        lines += ["", f"## {heading}", "", blurb, ""]
        rows = []
        for e in sorted(entries, key=lambda e: e.get("name", "").lower()):
            rows.append(
                [
                    f"**{e.get('name', '?')}**",
                    _repo_link(e.get("repo", "")),
                    e.get("note", "-") or "-",
                ]
            )
        lines.append(_table(["Name", "Repository", "Note"], rows))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "Documentation/docs/scientific_ecosystem/remote_modules.md",
    )
    parser.add_argument(
        "--classification",
        type=Path,
        default=repo_root / "Documentation/remote_modules_classification.yaml",
    )
    parser.add_argument(
        "--check", action="store_true", help="Fail if the output is stale."
    )
    args = parser.parse_args()

    in_tree = load_in_tree(repo_root / "Modules/Remote")
    data = load_data(args.classification)
    compliance = data.get("compliance_levels") or {}
    kind_sections = [
        (k["id"], k["heading"], k["blurb"]) for k in (data.get("kinds") or [])
    ]
    if not compliance or not kind_sections:
        raise SystemExit(
            f"{args.classification} must define 'compliance_levels' and 'kinds'."
        )

    # Drop curated entries whose repository is already an in-tree remote so a
    # repository is never listed twice.
    in_tree_repos = {m["repository"] for m in in_tree if m["repository"]}
    classified = [
        e
        for e in (data.get("repositories") or [])
        if _normalize_repo(e.get("repo", "")) not in in_tree_repos
    ]

    content = render(
        in_tree,
        classified,
        {str(k): v for k, v in compliance.items()},
        kind_sections,
        "Utilities/Maintenance/GenerateRemoteModuleList.py",
    )

    if args.check:
        current = (
            args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        )
        if current != content:
            raise SystemExit(
                f"{args.output} is out of date; regenerate with GenerateRemoteModuleList.py"
            )
        print(f"{args.output} is up to date ({len(in_tree)} in-tree modules).")
        return

    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(
        f"Wrote {args.output} ({len(in_tree)} in-tree modules, {len(classified)} classified repos)."
    )


if __name__ == "__main__":
    main()
