# auto include feature must be disable because all the following classes are in the same file
SET(WRAPPER_AUTO_INCLUDE_HEADERS OFF)
WRAP_INCLUDE("itkEventObject.h")

WRAP_NON_TEMPLATE_CLASS("itk::EventObject")
WRAP_NON_TEMPLATE_CLASS("itk::NoEvent")
WRAP_NON_TEMPLATE_CLASS("itk::AnyEvent")
WRAP_NON_TEMPLATE_CLASS("itk::DeleteEvent")
WRAP_NON_TEMPLATE_CLASS("itk::StartEvent")
WRAP_NON_TEMPLATE_CLASS("itk::EndEvent")
WRAP_NON_TEMPLATE_CLASS("itk::ProgressEvent")
WRAP_NON_TEMPLATE_CLASS("itk::ExitEvent")
WRAP_NON_TEMPLATE_CLASS("itk::ModifiedEvent")
WRAP_NON_TEMPLATE_CLASS("itk::IterationEvent")
WRAP_NON_TEMPLATE_CLASS("itk::PickEvent")
WRAP_NON_TEMPLATE_CLASS("itk::StartPickEvent")
WRAP_NON_TEMPLATE_CLASS("itk::EndPickEvent")
WRAP_NON_TEMPLATE_CLASS("itk::AbortCheckEvent")
WRAP_NON_TEMPLATE_CLASS("itk::UserEvent")
