WRAP_CLASS("itk::Matrix")
  WRAP_TEMPLATE("${ITKM_F}22" "${ITKT_F},2,2")
  WRAP_TEMPLATE("${ITKM_F}33" "${ITKT_F},3,3")
  WRAP_TEMPLATE("${ITKM_F}44" "${ITKT_F},4,4")
  
  WRAP_TEMPLATE("${ITKM_D}22" "${ITKT_D},2,2")
  WRAP_TEMPLATE("${ITKM_D}33" "${ITKT_D},3,3")
  WRAP_TEMPLATE("${ITKM_D}44" "${ITKT_D},4,4")
END_WRAP_CLASS()
