WRAP_INCLUDE("itkPolyLineParametricPath.h" POINTER)
WRAP_CLASS("itk::PathSource" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    WRAP_TEMPLATE("PLPP${d}" "itk::PolyLineParametricPath< ${d} >")
  endforeach(d)
END_WRAP_CLASS()
