itk_module(ITKLevelSets
  DEPENDS
    ITKImageFeature
    ITKFiniteDifference
    ITKDistanceMap
    ITKSignedDistanceFunction
    ITKAnisotropicSmoothing
    ITKThresholding
    ITKOptimizers
    ITKImageCompare
    ITKFastMarching
  TEST_DEPENDS
    ITKTestKernel
)
