itk_module(ITK-LevelSets
  DEPENDS
    ITK-ImageFeature
    ITK-FiniteDifference
    ITK-DistanceMap
    ITK-SignedDistanceFunction
    ITK-AnisotropicSmoothing
    ITK-Thresholding
    ITK-Optimizers
    ITK-ImageCompare
    ITK-FastMarching
  TEST_DEPENDS
    ITK-TestKernel
)
