WRAP_INCLUDE("itkVersorRigid3DTransform.h")
WRAP_INCLUDE("itkCenteredAffineTransform.h")
WRAP_INCLUDE("itkAffineTransform.h")
WRAP_INCLUDE("itkSimilarity2DTransform.h")
WRAP_INCLUDE("itkSimilarity3DTransform.h")
WRAP_CLASS("itk::CenteredTransformInitializer" POINTER)
    FILTER_DIMS(d 3)
    IF(d)
        FOREACH(t ${WRAP_ITK_SCALAR})
          WRAP_TEMPLATE("VR3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::VersorRigid3DTransform< ${ITKT_D} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
          WRAP_TEMPLATE("CA3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::CenteredAffineTransform< ${ITKT_D} , ${d} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
          WRAP_TEMPLATE("A3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::AffineTransform< ${ITKT_D} , ${d} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
          WRAP_TEMPLATE("S3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::Similarity3DTransform< ${ITKT_D} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
        ENDFOREACH(t)
    ENDIF(d)
    FILTER_DIMS(d 2)
    IF(d)
        FOREACH(t ${WRAP_ITK_SCALAR})
          WRAP_TEMPLATE("CA2DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::CenteredAffineTransform< ${ITKT_D} , ${d} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
          WRAP_TEMPLATE("A2DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::AffineTransform< ${ITKT_D} , ${d} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
          WRAP_TEMPLATE("S3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::Similarity2DTransform< ${ITKT_D} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
        ENDFOREACH(t)
    ENDIF(d)
END_WRAP_CLASS()
