WRAP_CLASS("itk::Similarity2DTransform" POINTER)
  WRAP_TEMPLATE("${ITKM_D}" "${ITKT_D}")
END_WRAP_CLASS()

WRAP_CLASS("itk::Similarity3DTransform" POINTER)
  WRAP_TEMPLATE("${ITKM_D}" "${ITKT_D}")
END_WRAP_CLASS()
