WRAP_INCLUDE("itkVersorRigid3DTransform.h")
WRAP_CLASS("itk::CenteredTransformInitializer" POINTER)
    FILTER_DIMS(d 3)
    IF(d)
        FOREACH(t ${WRAP_ITK_SCALAR})
          WRAP_TEMPLATE("VR3DT${ITKM_D}${ITKM_I${t}${d}}${ITKM_I${t}${d}}" "itk::VersorRigid3DTransform< ${ITKT_D} >,${ITKT_I${t}${d}},${ITKT_I${t}${d}}")
        ENDFOREACH(t)
    ENDIF(d)
END_WRAP_CLASS()
