WRAP_CLASS("itk::DisplacementFieldJacobianDeterminantFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(v ${WRAP_ITK_VECTOR_REAL})
      foreach(r ${WRAP_ITK_REAL})
        WRAP_TEMPLATE("${ITKM_I${v}${d}${d}}${ITKM_${r}}" "${ITKT_I${v}${d}${d}}, ${ITKT_${r}}")
      endforeach(r)
    endforeach(v)
  endforeach(d)
END_WRAP_CLASS()
