#!/usr/bin/env bash
set -ex
BUILD_DIR="${SRC_DIR}/build"

# Install Python wrapping artifacts (compiled extension modules + Python files).
# The PythonWrappingRuntimeLibraries component is isolated from the core C++
# runtime by building with -DWRAP_ITK_INSTALL_COMPONENT_IDENTIFIER=PythonWrapping,
# which directs all wrapping install() calls to this dedicated component.
cmake -DCOMPONENT=PythonWrappingRuntimeLibraries -P "${BUILD_DIR}/cmake_install.cmake"

# Generate a relocatable cmake_install.cmake and place it in the ITK cmake
# config directory.  ITKPythonPackage calls:
#   include("${ITK_BINARY_DIR}/cmake_install.cmake")
# with COMPONENT set to e.g. "ITKCommonPythonWheelRuntimeLibraries".
# Since this conda package uses WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER=PythonWrapping
# (different suffix), the build's cmake_install.cmake won't match.  This
# generated file bridges the gap: it maps the PythonWheel* component names that
# ITKPythonPackage expects to the files already installed under ${PREFIX}.
# The file uses CMAKE_CURRENT_LIST_DIR to derive the prefix at cmake time,
# making it fully relocatable across machines and prefix paths.

ITK_CMAKE_DIR=$(find "${PREFIX}/lib/cmake" -maxdepth 1 -name "ITK-*" -type d | head -1)
if [ -z "${ITK_CMAKE_DIR}" ]; then
    echo "ERROR: could not find ITK cmake config dir under ${PREFIX}/lib/cmake" >&2
    exit 1
fi

cat > "${ITK_CMAKE_DIR}/cmake_install.cmake" <<'CMAKE_EOF'
# Relocatable cmake_install.cmake for conda-installed ITK.
# Generated by ITKPythonPackage conda recipe (libitk-wrapping_install.sh).
# Maps ITKPythonPackage's PythonWheelRuntimeLibraries component names to the
# pre-installed files in the conda prefix.

# Derive the conda prefix from this file's own location:
#   <prefix>/lib/cmake/ITK-x.y/cmake_install.cmake
get_filename_component(_ipp_itk_cmake_dir "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(_ipp_cmake_dir     "${_ipp_itk_cmake_dir}" DIRECTORY)
get_filename_component(_ipp_lib_dir       "${_ipp_cmake_dir}"     DIRECTORY)
get_filename_component(_ipp_conda_prefix  "${_ipp_lib_dir}"       DIRECTORY)

if(DEFINED CMAKE_INSTALL_COMPONENT AND NOT CMAKE_INSTALL_COMPONENT STREQUAL "")
  set(_ipp_component "${CMAKE_INSTALL_COMPONENT}")
elseif(DEFINED COMPONENT AND NOT COMPONENT STREQUAL "")
  set(_ipp_component "${COMPONENT}")
else()
  return()
endif()

if(NOT _ipp_component MATCHES "PythonWheelRuntimeLibraries$")
  return()
endif()

# "ITKCommonPythonWheelRuntimeLibraries" -> "ITKCommon"
string(REGEX REPLACE "PythonWheelRuntimeLibraries$" "" _ipp_module "${_ipp_component}")

# Global package files (installed once via sentinel)
set(_ipp_sentinel "${CMAKE_INSTALL_PREFIX}/itk/.conda_global_done")
if(NOT EXISTS "${_ipp_sentinel}")
  file(GLOB _g "${_ipp_conda_prefix}/lib/python*/site-packages/itkConfig.py")
  if(_g)
    file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}" USE_SOURCE_PERMISSIONS)
  endif()
  file(GLOB _g "${_ipp_conda_prefix}/lib/python*/site-packages/itk/__init__.py")
  if(_g)
    file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS)
  endif()
  # itk/support/ — pure-Python API layer (lazy loading, template dispatch, etc.)
  file(GLOB _support_dir LIST_DIRECTORIES true
    "${_ipp_conda_prefix}/lib/python*/site-packages/itk/support"
  )
  if(_support_dir)
    file(INSTALL ${_support_dir} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS)
  endif()
  file(GLOB _g "${_ipp_conda_prefix}/lib/python*/site-packages/itk/Configuration/__init__.py")
  if(_g)
    file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk/Configuration" USE_SOURCE_PERMISSIONS)
  endif()
  file(WRITE "${_ipp_sentinel}" "done\n")
  message(STATUS "conda cmake_install: installed global itk package files")
endif()

# C extension (.abi3.so)
file(GLOB _so
  "${_ipp_conda_prefix}/lib/python*/site-packages/itk/_${_ipp_module}Python.abi3.so"
  "${_ipp_conda_prefix}/lib/python*/site-packages/itk/_${_ipp_module}Python*.so"
)
if(_so)
  file(INSTALL ${_so} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS)
endif()

# Python wrapper .py
file(GLOB _py
  "${_ipp_conda_prefix}/lib/python*/site-packages/itk/${_ipp_module}Python.py"
)
if(_py)
  file(INSTALL ${_py} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS)
endif()

# Configuration files
file(GLOB _cfg
  "${_ipp_conda_prefix}/lib/python*/site-packages/itk/Configuration/${_ipp_module}Config.py"
  "${_ipp_conda_prefix}/lib/python*/site-packages/itk/Configuration/${_ipp_module}_snake_case.py"
)
if(_cfg)
  file(INSTALL ${_cfg} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk/Configuration" USE_SOURCE_PERMISSIONS)
endif()

list(LENGTH _so _ipp_n)
message(STATUS "conda cmake_install: ${_ipp_component}: ${_ipp_n} .so + python files installed")
CMAKE_EOF

echo "Generated ${ITK_CMAKE_DIR}/cmake_install.cmake"
