@echo off
set BUILD_DIR=%SRC_DIR%\build

rem Install Python wrapping artifacts (compiled extension modules + Python files).
rem The PythonWrappingRuntimeLibraries component is isolated from the core C++
rem runtime by building with -DWRAP_ITK_INSTALL_COMPONENT_IDENTIFIER=PythonWrapping,
rem which directs all wrapping install() calls to this dedicated component.
cmake -DCOMPONENT=PythonWrappingRuntimeLibraries -P "%BUILD_DIR%\cmake_install.cmake"
if errorlevel 1 exit 1

rem Generate a relocatable cmake_install.cmake in the ITK cmake config directory.
rem ITKPythonPackage calls include("${ITK_BINARY_DIR}/cmake_install.cmake") with
rem COMPONENT set to e.g. "ITKCommonPythonWheelRuntimeLibraries".  This shim maps
rem those PythonWheel* names to files already installed under %PREFIX%.
rem On Windows, conda Python packages live at %PREFIX%\Lib\site-packages (one
rem level above %LIBRARY_PREFIX%) and extension modules use .pyd instead of .so.

for /d %%i in ("%LIBRARY_PREFIX%\lib\cmake\ITK-*") do set ITK_CMAKE_DIR=%%i
if "%ITK_CMAKE_DIR%"=="" (
    echo ERROR: could not find ITK cmake config dir under %LIBRARY_PREFIX%\lib\cmake 1>&2
    exit 1
)

rem Write the cmake_install.cmake via a temporary PowerShell script.
rem Using a PS1 temp file avoids cmd escaping issues with parentheses and
rem double quotes that appear throughout the cmake script content.
set GEN_PS1=%TEMP%\gen_itk_cmake_install_%RANDOM%.ps1

echo $dest = '%ITK_CMAKE_DIR%\cmake_install.cmake' > "%GEN_PS1%"
echo $content = @' >> "%GEN_PS1%"
echo # Relocatable cmake_install.cmake for conda-installed ITK (Windows). >> "%GEN_PS1%"
echo # Generated by ITKPythonPackage conda recipe (libitk-wrapping_install.bat). >> "%GEN_PS1%"
echo # Maps ITKPythonPackage's PythonWheelRuntimeLibraries component names to the >> "%GEN_PS1%"
echo # pre-installed files in the conda prefix. >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # On Windows the layout is: >> "%GEN_PS1%"
echo #   ^<LIBRARY_PREFIX^>/lib/cmake/ITK-x.y/cmake_install.cmake >> "%GEN_PS1%"
echo # where LIBRARY_PREFIX = PREFIX/Library, so walk up 4 levels to reach PREFIX. >> "%GEN_PS1%"
echo get_filename_component(_ipp_itk_cmake_dir "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY) >> "%GEN_PS1%"
echo get_filename_component(_ipp_cmake_dir     "${_ipp_itk_cmake_dir}" DIRECTORY) >> "%GEN_PS1%"
echo get_filename_component(_ipp_lib_dir       "${_ipp_cmake_dir}"     DIRECTORY) >> "%GEN_PS1%"
echo get_filename_component(_ipp_library_prefix "${_ipp_lib_dir}"      DIRECTORY) >> "%GEN_PS1%"
echo get_filename_component(_ipp_conda_prefix  "${_ipp_library_prefix}" DIRECTORY) >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo if(DEFINED CMAKE_INSTALL_COMPONENT AND NOT CMAKE_INSTALL_COMPONENT STREQUAL "") >> "%GEN_PS1%"
echo   set(_ipp_component "${CMAKE_INSTALL_COMPONENT}") >> "%GEN_PS1%"
echo elseif(DEFINED COMPONENT AND NOT COMPONENT STREQUAL "") >> "%GEN_PS1%"
echo   set(_ipp_component "${COMPONENT}") >> "%GEN_PS1%"
echo else() >> "%GEN_PS1%"
echo   return() >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo if(NOT _ipp_component MATCHES "PythonWheelRuntimeLibraries$") >> "%GEN_PS1%"
echo   return() >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # "ITKCommonPythonWheelRuntimeLibraries" -^> "ITKCommon" >> "%GEN_PS1%"
echo string(REGEX REPLACE "PythonWheelRuntimeLibraries$" "" _ipp_module "${_ipp_component}") >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # Global package files (installed once via sentinel) >> "%GEN_PS1%"
echo set(_ipp_sentinel "${CMAKE_INSTALL_PREFIX}/itk/.conda_global_done") >> "%GEN_PS1%"
echo if(NOT EXISTS "${_ipp_sentinel}") >> "%GEN_PS1%"
echo   file(GLOB _g "${_ipp_conda_prefix}/Lib/site-packages/itkConfig.py") >> "%GEN_PS1%"
echo   if(_g) >> "%GEN_PS1%"
echo     file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo   endif() >> "%GEN_PS1%"
echo   file(GLOB _g "${_ipp_conda_prefix}/Lib/site-packages/itk/__init__.py") >> "%GEN_PS1%"
echo   if(_g) >> "%GEN_PS1%"
echo     file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo   endif() >> "%GEN_PS1%"
echo   # itk/support/ -- pure-Python API layer (lazy loading, template dispatch, etc.) >> "%GEN_PS1%"
echo   file(GLOB _support_dir LIST_DIRECTORIES true >> "%GEN_PS1%"
echo     "${_ipp_conda_prefix}/Lib/site-packages/itk/support" >> "%GEN_PS1%"
echo   ) >> "%GEN_PS1%"
echo   if(_support_dir) >> "%GEN_PS1%"
echo     file(INSTALL ${_support_dir} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo   endif() >> "%GEN_PS1%"
echo   file(GLOB _g "${_ipp_conda_prefix}/Lib/site-packages/itk/Configuration/__init__.py") >> "%GEN_PS1%"
echo   if(_g) >> "%GEN_PS1%"
echo     file(INSTALL ${_g} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk/Configuration" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo   endif() >> "%GEN_PS1%"
echo   file(WRITE "${_ipp_sentinel}" "done\n") >> "%GEN_PS1%"
echo   message(STATUS "conda cmake_install: installed global itk package files") >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # C extension (.pyd) >> "%GEN_PS1%"
echo file(GLOB _ext >> "%GEN_PS1%"
echo   "${_ipp_conda_prefix}/Lib/site-packages/itk/_${_ipp_module}Python.pyd" >> "%GEN_PS1%"
echo ) >> "%GEN_PS1%"
echo if(_ext) >> "%GEN_PS1%"
echo   file(INSTALL ${_ext} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # Python wrapper .py >> "%GEN_PS1%"
echo file(GLOB _py >> "%GEN_PS1%"
echo   "${_ipp_conda_prefix}/Lib/site-packages/itk/${_ipp_module}Python.py" >> "%GEN_PS1%"
echo ) >> "%GEN_PS1%"
echo if(_py) >> "%GEN_PS1%"
echo   file(INSTALL ${_py} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo # Configuration files >> "%GEN_PS1%"
echo file(GLOB _cfg >> "%GEN_PS1%"
echo   "${_ipp_conda_prefix}/Lib/site-packages/itk/Configuration/${_ipp_module}Config.py" >> "%GEN_PS1%"
echo   "${_ipp_conda_prefix}/Lib/site-packages/itk/Configuration/${_ipp_module}_snake_case.py" >> "%GEN_PS1%"
echo ) >> "%GEN_PS1%"
echo if(_cfg) >> "%GEN_PS1%"
echo   file(INSTALL ${_cfg} DESTINATION "${CMAKE_INSTALL_PREFIX}/itk/Configuration" USE_SOURCE_PERMISSIONS) >> "%GEN_PS1%"
echo endif() >> "%GEN_PS1%"
echo. >> "%GEN_PS1%"
echo list(LENGTH _ext _ipp_n) >> "%GEN_PS1%"
echo message(STATUS "conda cmake_install: ${_ipp_component}: ${_ipp_n} .pyd + python files installed") >> "%GEN_PS1%"
echo '@ >> "%GEN_PS1%"
echo [System.IO.File]::WriteAllText($dest, $content) >> "%GEN_PS1%"

powershell -NoProfile -ExecutionPolicy Bypass -File "%GEN_PS1%"
if errorlevel 1 exit 1
del "%GEN_PS1%"

echo Generated %ITK_CMAKE_DIR%\cmake_install.cmake
