WRAP_CLASS("itk::LabelMapMaskImageFilter" POINTER)
  foreach(t ${WRAP_ITK_SCALAR})
    foreach(d ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_LM${d}}${ITKM_I${t}${d}}" "${ITKT_LM${d}}, ${ITKT_I${t}${d}}")
    endforeach(d)
  endforeach(t)
END_WRAP_CLASS()
