WRAP_CLASS("itk::LabelMapToBinaryImageFilter" POINTER)
  foreach(t ${WRAP_ITK_USIGN_INT})
    foreach(d ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_LM${d}}${ITKM_I${t}${d}}" "${ITKT_LM${d}}, ${ITKT_I${t}${d}}")
    endforeach(d)
  endforeach(t)
END_WRAP_CLASS()
