WRAP_CLASS("itk::GradientVectorFlowImageFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_VECTOR_REAL})
      string(REGEX REPLACE "V" "" t2 "${t}")
      WRAP_TEMPLATE("${ITKM_I${t}${d}${d}}${ITKM_I${t}${d}${d}}${ITKM_${t2}}" "${ITKT_I${t}${d}${d}}, ${ITKT_I${t}${d}${d}}, ${ITKT_${t2}}")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
