WRAP_CLASS("itk::BSplineInterpolateImageFunction" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_SCALAR})
      # WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}${ITKM_${t}}" "${ITKT_I${t}${d}},${ITKT_D},${ITKT_${t}}")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
