SET(WRAPPER_AUTO_INCLUDE_HEADERS OFF)
WRAP_INCLUDE("itkWindowedSincInterpolateImageFunction.h")

WRAP_CLASS("itk::WindowedSincInterpolateImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      FOREACH(r RANGE 3 6)
        WRAP_TEMPLATE("${ITKM_I${t}${d}}HammingWindow${r}ConstantBoundaryCondition${ITKM_D}"   "${ITKT_I${t}${d}},${r},itk::Function::HammingWindowFunction<${r}  > ,itk::ConstantBoundaryCondition<${ITKT_I${t}${d}} > ,${ITKT_D}")
        WRAP_TEMPLATE("${ITKM_I${t}${d}}CosineWindow${r}ConstantBoundaryCondition${ITKM_D}"    "${ITKT_I${t}${d}},${r},itk::Function::CosineWindowFunction<${r}   > ,itk::ConstantBoundaryCondition<${ITKT_I${t}${d}} > ,${ITKT_D}")
        WRAP_TEMPLATE("${ITKM_I${t}${d}}WelchWindow${r}ConstantBoundaryCondition${ITKM_D}"     "${ITKT_I${t}${d}},${r},itk::Function::WelchWindowFunction<${r}    > ,itk::ConstantBoundaryCondition<${ITKT_I${t}${d}} > ,${ITKT_D}")
        WRAP_TEMPLATE("${ITKM_I${t}${d}}LanczosWindow${r}ConstantBoundaryCondition${ITKM_D}"   "${ITKT_I${t}${d}},${r},itk::Function::LanczosWindowFunction<${r}  > ,itk::ConstantBoundaryCondition<${ITKT_I${t}${d}} > ,${ITKT_D}")
        WRAP_TEMPLATE("${ITKM_I${t}${d}}BlackmanWindow${r}ConstantBoundaryCondition${ITKM_D}"  "${ITKT_I${t}${d}},${r},itk::Function::BlackmanWindowFunction<${r} > ,itk::ConstantBoundaryCondition<${ITKT_I${t}${d}} > ,${ITKT_D}")
      ENDFOREACH(r)
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()

