WRAP_CLASS("itk::RealAndImaginaryToComplexImageFilter" POINTER_WITH_SUPERCLASS)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_REAL})
#      foreach(c ${WRAP_ITK_COMPLEX_REAL})
#        WRAP_TEMPLATE("${ITKM_${t}}${ITKM_${t}}${ITKM_${c}}${d}" "${ITKT_${t}},${ITKT_${t}},${ITKT_${c}},${d}")
#      endforeach(c)

      if(WRAP_complex_float)
         WRAP_TEMPLATE("${ITKM_${t}}${ITKM_${t}}${ITKM_F}${d}" "${ITKT_${t}},${ITKT_${t}},${ITKT_F},${d}")
      endif(WRAP_complex_float)

      if(WRAP_complex_double)
         WRAP_TEMPLATE("${ITKM_${t}}${ITKM_${t}}${ITKM_D}${d}" "${ITKT_${t}},${ITKT_${t}},${ITKT_L},${d}")
      endif(WRAP_complex_double)
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
