if( VGUI_FOUND )
  set( HAS_VGUI "YES" )
  find_package(OpenGL)
  include_directories( ${OPENGL_INCLUDE_PATH} )
  add_definitions( -DHAS_OPENGL)
  find_package(GTK)
  if(VGUI_USE_GTK)
    link_libraries( ${GTK_LIBRARIES} ${OPENGL_LIBRARIES} )
  endif()
endif()

if( VXL_VGUI_FOUND )
  set( HAS_VGUI "YES" )
  include_directories( ${VXL_VGUI_INCLUDE_DIR} )
  link_libraries( ${VXL_VGUI_LIBRARIES} )
endif()
