jobs:
- job: Windows
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 300
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: |
        git clone -b dashboard --single-branch https://github.com/InsightSoftwareConsortium/ITK.git ITK-dashboard

        pip3 install ninja

        cmake --version

        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set BUILD_SHARED_LIBS=ON
        set BUILD_EXAMPLES=OFF
        set CC=cl.exe
        set CXX=cl.exe

        ctest -S ITK-dashboard/azure_dashboard.cmake -VV -j 4
      displayName: Build and Test
      workingDirectory: $(Agent.BuildDirectory)
