trigger:
  branches:
    include:
    - master
    - release*
jobs:
- job: Windows
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 300
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: |
        git clone -b dashboard --single-branch https://github.com/thewtex/ITK.git ITK-dashboard

        pip3 install ninja numpy

        cmake --version

        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set BUILD_EXAMPLES=OFF
        set CTEST_BUILD_CONFIGURATION=MinSizeRel
        set BUILD_SHARED_LIBS=ON
        set ITK_WRAP_PYTHON=ON
        set ITK_BUILD_DEFAULT_MODULES=OFF
        set CC=cl.exe
        set CXX=cl.exe

        ctest -S ITK-dashboard/azure_dashboard.cmake -VV -j 4
      displayName: Build and Test
      workingDirectory: $(Agent.BuildDirectory)
