WRAP_CLASS("itk::GradientVectorFlowImageFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_VECTOR_REAL})
      STRING(REGEX REPLACE "V" "" t2 "${t}") 
      WRAP_TEMPLATE("${ITKM_I${t}${d}${d}}${ITKM_I${t}${d}${d}}${ITKM_${t2}}" "${ITKT_I${t}${d}${d}}, ${ITKT_I${t}${d}${d}}, ${ITKT_${t2}}")
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
