/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:
  Language:  C++
  Date:
  Version:


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkImageSpatialObject.txx"
#include "itkSpatialObject.txx"
#include "itkSpatialObjectProperty.txx"
#include "itkTubeNetworkSpatialObject.h"
#include "itkTubeSpatialObjectPoint.h"
#include "itkTubeSpatialObject.txx"
#include "itkEllipseSpatialObject.txx"
#include "itkBlobSpatialObject.txx"
#include "itkLineSpatialObject.txx"
#include "itkLineSpatialObjectPoint.txx"
#include "itkNDimensionalSpatialObject.txx"
#include "itkScene.txx"
#include "itkSpatialObjectPoint.txx"
#include "itkSurfaceSpatialObject.txx"
#include "itkSurfaceSpatialObjectPoint.txx"
#include "itkTubeSpatialObject.txx"
#include "itkTubeSpatialObjectPoint.txx"

int main ( int argc, char* argv )
{
  
  return 0;
}

