WRAP_CLASS("itk::BayesianClassifierInitializationImageFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      FOREACH(t3 ${WRAP_ITK_REAL})
        WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_${t3}}" "${ITKT_I${t}${d}}, ${ITKT_${t3}}")
      ENDFOREACH(t3)
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
