WRAP_CLASS("itk::BayesianClassifierImageFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      FOREACH(t2 ${WRAP_ITK_INT})
        FOREACH(t3 ${WRAP_ITK_REAL})
          WRAP_TEMPLATE("${ITKM_VI${t}${d}}${ITKM_${t2}}${ITKM_${t3}}" "${ITKT_VI${t}${d}}, ${ITKT_${t2}}, ${ITKT_${t3}}")
        ENDFOREACH(t3)
      ENDFOREACH(t2)
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
