#include <vnl/vnl_matrix_fixed.txx>

#if defined(VCL_WIN32) || defined(VCL_SUNPRO_CC)
// don't do anything.
#else
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 2,2,2);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 2,3,2);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 2,3,3);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 3,3,2);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 3,3,3);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 3,3,4);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 3,4,4);
VNL_MATRIX_FIXED_PAIR_INSTANTIATE(double, 4,4,4);
#endif
