/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    itkNeuralNetworksHeaderTest.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) Insight Software Consortium. All rights reserved.
  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even 
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkBackPropagationLayer.h"
#include "itkBackPropagationLayer.txx"
#include "itkBatchSupervisedTrainingFunction.h"
#include "itkBatchSupervisedTrainingFunction.txx"
#include "itkCompletelyConnectedWeightSet.h"
#include "itkCompletelyConnectedWeightSet.txx"
#include "itkErrorBackPropagationLearningFunctionBase.h"
#include "itkErrorBackPropagationLearningFunctionBase.txx"
#include "itkErrorBackPropagationLearningWithMomentum.h"
#include "itkErrorBackPropagationLearningWithMomentum.txx"
#include "itkErrorFunctionBase.h"
#include "itkGaussianRadialBasisFunction.h"
#include "itkGaussianRadialBasisFunction.txx"
#include "itkGaussianTransferFunction.h"
#include "itkHardLimitTransferFunction.h"
#include "itkHardLimitTransferFunction.txx"
#include "itkIdentityTransferFunction.h"
#include "itkIdentityTransferFunction.txx"
#include "itkInputFunctionBase.h"
#include "itkLayerBase.h"
#include "itkLayerBase.txx"
#include "itkLogSigmoidTransferFunction.h"
#include "itkLogSigmoidTransferFunction.txx"
#include "itkMeanSquaredErrorFunction.h"
#include "itkMeanSquaredErrorFunction.txx"
#include "itkMultilayerNeuralNetworkBase.h"
#include "itkMultilayerNeuralNetworkBase.txx"
#include "itkMultiquadricRadialBasisFunction.h"
#include "itkMultiquadricRadialBasisFunction.txx"
#include "itkNeuralNetworkObject.h"
#include "itkNeuralNetworkObject.txx"
#include "itkOneHiddenLayerBackPropagationNeuralNetwork.h"
#include "itkOneHiddenLayerBackPropagationNeuralNetwork.txx"
//#include "itkPerceptron.h"
//#include "itkPerceptron.txx"
//#include "itkPerceptronLayer.h"
//#include "itkPerceptronLayer.txx"
//#include "itkPerceptronLearningFunction.h"
//#include "itkPerceptronLearningFunction.txx"
#include "itkProductInputFunction.h"
#include "itkProductInputFunction.txx"
#include "itkQuickPropLearningRule.h"
#include "itkQuickPropLearningRule.txx"
#include "itkRadialBasisFunctionBase.h"
#include "itkRBFBackPropagationLearningFunction.h"
#include "itkRBFBackPropagationLearningFunction.txx"
#include "itkRBFLayer.h"
#include "itkRBFLayer.txx"
#include "itkRBFNetwork.h"
#include "itkRBFNetwork.txx"
#include "itkSigmoidTransferFunction.h"
#include "itkSigmoidTransferFunction.txx"
#include "itkSignedHardLimitTransferFunction.h"
#include "itkSignedHardLimitTransferFunction.txx"
#include "itkSquaredDifferenceErrorFunction.h"
#include "itkSquaredDifferenceErrorFunction.txx"
#include "itkSumInputFunction.h"
#include "itkSumInputFunction.txx"
#include "itkSymmetricSigmoidTransferFunction.h"
#include "itkSymmetricSigmoidTransferFunction.txx"
#include "itkTanHTransferFunction.h"
#include "itkTanHTransferFunction.txx"
#include "itkTanSigmoidTransferFunction.h"
#include "itkTanSigmoidTransferFunction.txx"
#include "itkTrainingFunctionBase.h"
#include "itkTrainingFunctionBase.txx"
#include "itkTransferFunctionBase.h"
#include "itkTwoHiddenLayerBackPropagationNeuralNetwork.h"
#include "itkTwoHiddenLayerBackPropagationNeuralNetwork.txx"
#include "itkWeightSetBase.h"
#include "itkWeightSetBase.txx"

int main ( int , char*  )
{
  return 0;
}

