/*=========================================================================
 *
 *  Copyright Insight Software Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>

#include "itkAggregateLabelMapFilter.hxx"
#include "itkAreaClosingImageFilter.h"
#include "itkAreaOpeningImageFilter.h"
#include "itkAttributeKeepNObjectsLabelMapFilter.hxx"
#include "itkAttributeLabelObject.h"
#include "itkAttributeMorphologyBaseImageFilter.hxx"
#include "itkAttributeOpeningLabelMapFilter.hxx"
#include "itkAttributePositionLabelMapFilter.hxx"
#include "itkAttributeRelabelLabelMapFilter.hxx"
#include "itkAttributeSelectionLabelMapFilter.hxx"
#include "itkAttributeUniqueLabelMapFilter.hxx"
#include "itkAutoCropLabelMapFilter.hxx"
#include "itkAutumnColormapFunction.hxx"
#include "itkBinaryClosingByReconstructionImageFilter.hxx"
#include "itkBinaryFillholeImageFilter.hxx"
#include "itkBinaryGrindPeakImageFilter.hxx"
#include "itkBinaryImageToLabelMapFilter.hxx"
#include "itkBinaryImageToShapeLabelMapFilter.hxx"
#include "itkBinaryImageToStatisticsLabelMapFilter.hxx"
#include "itkBinaryMorphologicalClosingImageFilter.hxx"
#include "itkBinaryMorphologicalOpeningImageFilter.hxx"
#include "itkBinaryNotImageFilter.h"
#include "itkBinaryOpeningByReconstructionImageFilter.hxx"
#include "itkBinaryReconstructionByDilationImageFilter.hxx"
#include "itkBinaryReconstructionByErosionImageFilter.hxx"
#include "itkBinaryReconstructionLabelMapFilter.hxx"
#include "itkBinaryShapeKeepNObjectsImageFilter.hxx"
#include "itkBinaryShapeOpeningImageFilter.hxx"
#include "itkBinaryStatisticsKeepNObjectsImageFilter.hxx"
#include "itkBinaryStatisticsOpeningImageFilter.hxx"
#include "itkBlueColormapFunction.hxx"
#include "itkBoxMeanImageFilter.hxx"
#include "itkBoxSigmaImageFilter.hxx"
#include "itkBoxUtilities.h"
#include "itkBruker2DSEQImageIO.h"
#include "itkBruker2DSEQImageIOFactory.h"
#include "itkBSplineControlPointImageFilter.hxx"
#include "itkBSplineControlPointImageFunction.hxx"
#include "itkBSplineDeformableTransformInitializer.hxx"
#include "itkBSplineScatteredDataPointSetToImageFilter.hxx"
#include "itkChangeLabelLabelMapFilter.hxx"
#include "itkChangeRegionLabelMapFilter.hxx"
#include "itkColormapFunction.h"
#include "itkComplexBSplineInterpolateImageFunction.hxx"
#include "itkCompositeTransform.hxx"
#include "itkConformalFlatteningMeshFilter.hxx"
#include "itkConstrainedRegionBasedLevelSetFunctionSharedData.h"
#include "itkContourExtractor2DImageFilter.hxx"
#include "itkConvolutionImageFilter.hxx"
#include "itkCoolColormapFunction.hxx"
#include "itkCopperColormapFunction.hxx"
#include "itkCoxDeBoorBSplineKernelFunction.hxx"
#include "itkCropLabelMapFilter.hxx"
#include "itkCustomColormapFunction.hxx"
#include "itkDeformationFieldTransform.hxx"
#include "itkDiffeomorphicDemonsRegistrationFilter.hxx"
#include "itkDirectFourierReconstructionImageToImageFilter.hxx"
#include "itkDiscreteGaussianDerivativeImageFilter.hxx"
#include "itkDiscreteGaussianDerivativeImageFunction.hxx"
#include "itkDiscreteGradientMagnitudeGaussianImageFunction.hxx"
#include "itkDiscreteHessianGaussianImageFunction.hxx"
#include "itkESMDemonsRegistrationFunction.hxx"
#include "itkExponentialDeformationFieldImageFilter.hxx"
#include "itkFastApproximateRankImageFilter.h"
#include "itkFastSymmetricForcesDemonsRegistrationFilter.hxx"
#include "itkGaborImageSource.hxx"
#include "itkGaborKernelFunction.h"
#include "itkGaussianDerivativeOperator.hxx"
#include "itkGenericUtilities.h"
#include "itkGeometryUtilities.h"
#include "itkGreenColormapFunction.hxx"
#include "itkGreyColormapFunction.hxx"
#include "itkGridForwardWarpImageFilter.hxx"
#include "itkGridImageSource.hxx"
#include "itkHessianToObjectnessMeasureImageFilter.hxx"
#include "itkHotColormapFunction.hxx"
#include "itkHSVColormapFunction.hxx"
#include "itkImageKernelOperator.hxx"
#include "itkImageToPathFilter.hxx"
#include "itkInPlaceLabelMapFilter.hxx"
#include "itkJetColormapFunction.hxx"
#include "itkJPEG2000ImageIO.h"
#include "itkJPEG2000ImageIOFactory.h"
#include "itkKappaSigmaThresholdImageCalculator.hxx"
#include "itkKappaSigmaThresholdImageFilter.hxx"
#include "itkLabelGeometryImageFilter.hxx"
#include "itkLabelImageToLabelMapFilter.hxx"
#include "itkLabelImageToShapeLabelMapFilter.hxx"
#include "itkLabelImageToStatisticsLabelMapFilter.hxx"
#include "itkLabelMap.hxx"
#include "itkLabelMapContourOverlayImageFilter.hxx"
#include "itkLabelMapFilter.hxx"
#include "itkLabelMapMaskImageFilter.hxx"
#include "itkLabelMapOverlayImageFilter.hxx"
#include "itkLabelMapToAttributeImageFilter.hxx"
#include "itkLabelMapToBinaryImageFilter.hxx"
#include "itkLabelMapToLabelImageFilter.hxx"
#include "itkLabelMapToRGBImageFilter.hxx"
#include "itkLabelMapUtilities.h"
#include "itkLabelObject.hxx"
#include "itkLabelObjectAccessors.h"
#include "itkLabelObjectLine.hxx"
#include "itkLabelObjectLineComparator.h"
#include "itkLabelOverlayFunctor.h"
#include "itkLabelOverlayImageFilter.hxx"
#include "itkLabelSelectionLabelMapFilter.h"
#include "itkLabelShapeKeepNObjectsImageFilter.hxx"
#include "itkLabelShapeOpeningImageFilter.hxx"
#include "itkLabelStatisticsKeepNObjectsImageFilter.hxx"
#include "itkLabelStatisticsOpeningImageFilter.hxx"
#include "itkLabelToRGBFunctor.h"
#include "itkLabelToRGBImageFilter.hxx"
#include "itkLabelUniqueLabelMapFilter.h"
#include "itkMagnitudeAndPhaseToComplexImageFilter.h"
#include "itkMaskedMovingHistogramImageFilter.hxx"
#include "itkMaskedRankImageFilter.hxx"
#include "itkMergeLabelMapFilter.hxx"
#include "itkMiniPipelineSeparableImageFilter.hxx"
#include "itkMorphologicalWatershedFromMarkersImageFilter.hxx"
#include "itkMorphologicalWatershedImageFilter.hxx"
#include "itkMRCHeaderObject.h"
#include "itkMRCImageIO.h"
#include "itkMRCImageIOFactory.h"
#include "itkMultiphaseDenseFiniteDifferenceImageFilter.hxx"
#include "itkMultiphaseFiniteDifferenceImageFilter.hxx"
#include "itkMultiphaseSparseFiniteDifferenceImageFilter.hxx"
#include "itkMultiScaleHessianBasedMeasureImageFilter.hxx"
#include "itkN4MRIBiasFieldCorrectionImageFilter.hxx"
#include "itkNeuralNetworkFileReader.hxx"
#include "itkNeuralNetworkFileWriter.hxx"
#include "itkObjectByObjectLabelMapFilter.hxx"
#include "itkObjectToObjectMetric.hxx"
#include "itkOverUnderColormapFunction.hxx"
#include "itkPadLabelMapFilter.hxx"
#include "itkRankHistogram.h"
#include "itkRankImageFilter.hxx"
#include "itkRedColormapFunction.hxx"
#include "itkRegionalMaximaImageFilter.hxx"
#include "itkRegionalMinimaImageFilter.hxx"
#include "itkRegionBasedLevelSetFunction.hxx"
#include "itkRegionBasedLevelSetFunctionData.hxx"
#include "itkRegionBasedLevelSetFunctionSharedData.h"
#include "itkRegionFromReferenceLabelMapFilter.hxx"
#include "itkRelabelLabelMapFilter.h"
#include "itkRobustAutomaticThresholdCalculator.hxx"
#include "itkRobustAutomaticThresholdImageFilter.hxx"
#include "itkScalarChanAndVeseDenseLevelSetImageFilter.hxx"
#include "itkScalarChanAndVeseLevelSetFunction.hxx"
#include "itkScalarChanAndVeseLevelSetFunctionData.h"
#include "itkScalarChanAndVeseSparseLevelSetImageFilter.hxx"
#include "itkScalarRegionBasedLevelSetFunction.hxx"
#include "itkScalarToRGBColormapImageFilter.hxx"
#include "itkShapedFloodFilledFunctionConditionalConstIterator.hxx"
#include "itkShapedFloodFilledImageFunctionConditionalConstIterator.hxx"
#include "itkShapedFloodFilledImageFunctionConditionalIterator.h"
#include "itkShapeKeepNObjectsLabelMapFilter.hxx"
#include "itkShapeLabelMapFilter.hxx"
#include "itkShapeLabelObject.h"
#include "itkShapeLabelObjectAccessors.h"
#include "itkShapeOpeningLabelMapFilter.hxx"
#include "itkShapePositionLabelMapFilter.hxx"
#include "itkShapeRelabelImageFilter.hxx"
#include "itkShapeRelabelLabelMapFilter.hxx"
#include "itkShapeUniqueLabelMapFilter.hxx"
#include "itkShiftScaleLabelMapFilter.hxx"
#include "itkSliceBySliceImageFilter.hxx"
#include "itkSpringColormapFunction.hxx"
#include "itkStatisticsKeepNObjectsLabelMapFilter.hxx"
#include "itkStatisticsLabelMapFilter.hxx"
#include "itkStatisticsLabelObject.h"
#include "itkStatisticsLabelObjectAccessors.h"
#include "itkStatisticsOpeningLabelMapFilter.hxx"
#include "itkStatisticsPositionLabelMapFilter.hxx"
#include "itkStatisticsRelabelImageFilter.hxx"
#include "itkStatisticsRelabelLabelMapFilter.hxx"
#include "itkStatisticsUniqueLabelMapFilter.hxx"
#include "itkStochasticFractalDimensionImageFilter.hxx"
#include "itkSummerColormapFunction.hxx"
#include "itkTransformToDeformationFieldSource.hxx"
#include "itkUnconstrainedRegionBasedLevelSetFunctionSharedData.h"
#include "itkValuedRegionalExtremaImageFilter.hxx"
#include "itkValuedRegionalMaximaImageFilter.h"
#include "itkValuedRegionalMinimaImageFilter.h"
#include "itkVectorCentralDifferenceImageFunction.hxx"
#include "itkVectorLinearInterpolateNearestNeighborExtrapolateImageFunction.hxx"
#include "itkVoxBoCUBImageIO.h"
#include "itkVoxBoCUBImageIOFactory.h"
#include "itkWarpHarmonicEnergyCalculator.hxx"
#include "itkWinterColormapFunction.hxx"

int itkReviewHeaderTest ( int , char * [] )
{
  return EXIT_SUCCESS;
}
