itk_module(ITK-Deprecated DEPENDS
ITK-AnisotropicSmoothing
ITK-AntiAlias
ITK-BiasCorrection
ITK-BioCell
ITK-Blox
ITK-Classifiers
ITK-Common
ITK-ConnectedComponents
ITK-CurvatureFlow
ITK-DeformableMesh
ITK-DeformationField
ITK-DiffusionTensorImage
ITK-DistanceMap
ITK-DICOMParser
ITK-Eigen
ITK-FEM
ITK-FEMRegistration
ITK-FFT
ITK-FiniteDifference
ITK-ImageAdaptors
ITK-ImageCompare
ITK-ImageCompose
ITK-ImageFeature
ITK-ImageFilterBase
ITK-ImageFunction
ITK-ImageGradient
ITK-ImageGrid
ITK-ImageIntensity
ITK-ImageLabel
ITK-ImageStatistics
ITK-IO-Base
ITK-IO-BioRad
ITK-IO-BMP
ITK-IO-GDCM
ITK-IO-GE
ITK-IO-GIPL
ITK-IO-IPL
ITK-IO-JPEG
ITK-IO-LSM
ITK-IO-Meta
ITK-IO-NIFTI
ITK-IO-NRRD
ITK-IO-PNG
ITK-IO-RAW
ITK-IO-Siemens
ITK-IO-SpatialObjects
ITK-IO-Stimulate
ITK-IO-TIFF
ITK-IO-VTK
ITK-IO-XML
ITK-KLMRegionGrowing
ITK-LabelVoting
ITK-LevelSets
ITK-MarkovRandomFieldsClassifiers
ITK-MathematicalMorphology
ITK-Mesh
ITK-NarrowBand
ITK-NeuralNetworks
ITK-Optimizers
ITK-Path
ITK-PDEDeformableRegistration
ITK-Polynomials
ITK-QuadEdgeMesh
ITK-QuadEdgeMeshFiltering
ITK-RegionGrowing
ITK-RegistrationCommon
ITK-SignedDistanceFunction
ITK-Smoothing
ITK-SpatialFunction
ITK-SpatialObjects
ITK-Statistics
ITK-Thresholding
ITK-Transform
ITK-Voronoi
ITK-VTK
ITK-Watersheds
TEST_DEPENDS ITK-TestKernel
)
