WRAP_CLASS("itk::DirectFourierReconstructionImageToImageFilter" POINTER)
  FILTER_DIMS(d 3)
  if(d)
    foreach(t ${WRAP_ITK_REAL})
      WRAP_TEMPLATE("${ITKM_${t}}${ITKM_${t}}" "${ITKT_${t}}, ${ITKT_${t}}")
    endforeach(t)
  endif(d)
END_WRAP_CLASS()
