# =========================================================================
# 
#   Program:   Insight Segmentation & Registration Toolkit
#   Module:    BuildHeaderTest.tcl
#   Language:  Tcl
#   Date:      $Date$
#   Version:   $Revision$
# 
# 
#   Copyright (c) 2000 National Library of Medicine
#   All rights reserved.
# 
#   See COPYRIGHT.txt for copyright details.
# 
# =========================================================================*/

set Header {/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit (ITK)
  Module:    BuildHeaderTest.tcl
  Language:  C++
  Date:      $$
  Version:   $$


Copyright (c) 2000 National Library of Medicine
All rights reserved.

See COPYRIGHT.txt for copyright details.

=========================================================================*/
#include <iostream>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight
}

set Trailer "
int main ( int argc, char* argv[] )
{
  
  return 0;
}
"

set D [lsort [glob Code/*]]
set Directories ""
foreach d $D \
{
  if { [file tail $d] != "CVS" && [file isdirectory $d]} \
  {
    lappend Directories [file tail $d]
  }
}

foreach Directory $Directories \
{
  if { ![file exists [file join Testing Code $Directory]] } \
  {
    continue
  }
  set f [open [file join Testing Code $Directory itkHeaderTest.cxx] w]
  puts $f $Header
  foreach File [lsort [glob [file join Code $Directory *.h]]] \
  {
    puts $f "#include \"[file tail $File]\""
  }
  puts $f $Trailer
  close $f
}

