WRAP_CLASS("itk::InterpolateImageFunction" POINTER)
  UNIQUE(types "${WRAP_ITK_SCALAR};UC")
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_F}" "${ITKT_I${t}${d}},${ITKT_F}")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
