#!/bin/sh
#==========================================================================
#
#   Copyright Insight Software Consortium
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0.txt
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#==========================================================================*/
#==========================================================================
#
#   Portions of this file are subject to the VTK Toolkit Version 3 copyright.
#
#   Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
#
#   For complete copyright, license and disclaimer of warranty information
#   please refer to the NOTICE file at the top of the ITK source tree.
#
#==========================================================================*/

#
# This is a shell script driving the ITK Tcl wrapper executable.  It
# sets up the environment and then executes the real executable.
# Alternatively, if the first command line argument is "--run", the rest
# of the command line will be invoked as a command in the proper
# environment.
#
# The real executable is located relative to this script in
#   ../lib/InsightToolkit
#

ITKWISH_Usage()
{
  echo "Insight Segmentation & Registration Toolkit (http://www.itk.org)"
  echo "This is the Tcl wrapper executable driver."
  echo ""
  echo "Usage:"
  echo "  itkwish           = Run itkwish interactively as a Tcl interpreter."
  echo "  itkwish foo.tcl   = Run \"foo.tcl\" in the ITK Tcl interpreter."
  echo "  itkwish --run ... = Run command \"...\" in the itkwish environment."
  echo ""
  echo "Example commands:"
  echo "  \"itkwish\""
  echo "    Provides a tcl prompt "%" from which ITK scripts can be written"
  echo "    interactively."
  echo ""
  echo "  \"itkwish myITKScript.tcl\""
  echo "    Runs the myITKScript.tcl script in the ITK Tcl interpreter.."
  echo ""
  echo "  \"itkwish --run wish\""
  echo "    Runs wish in an environment in which the ITK packages can be"
  echo "    loaded with \"package require InsightToolkit\"."
}

ITKWISH_SELFDIR=`cd \`echo "$0" | sed -n '/\//{s/\/[^\/]*$//;p;}'\`;pwd`

if [ -d "${ITKWISH_SELFDIR}/../lib/InsightToolkit" ]; then : ; else
  ITKWISH_Usage
  echo ""
  echo "Error:"
  echo "  This script is meant to be used from an itk installation directory."
  echo "  It will not run from the itk source tree."
  exit 1
fi

ITKWISH_LIBDIR=`cd "${ITKWISH_SELFDIR}/../lib/InsightToolkit"; pwd`

# Setup environment.
case "`uname`" in
Darwin)
  if [ -z "$DYLD_LIBRARY_PATH" ]; then
    export DYLD_LIBRARY_PATH="$ITKWISH_LIBDIR"
  else
    export DYLD_LIBRARY_PATH="$ITKWISH_LIBDIR:$DYLD_LIBRARY_PATH"
  fi
  ;;
*)
  if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH="$ITKWISH_LIBDIR"
  else
    export LD_LIBRARY_PATH="$ITKWISH_LIBDIR:$LD_LIBRARY_PATH"
  fi
esac

if [ -z "$TCLLIBPATH" ]; then
  export TCLLIBPATH="\"$ITKWISH_LIBDIR\""
else
  export TCLLIBPATH="\"$ITKWISH_LIBDIR\" $TCLLIBPATH"
fi

if [ "$1" = "--help" ]; then
  # Display usage.
  ITKWISH_Usage
  exit
elif [ "$1" = "--run" ]; then
  # Skip the "--run" argument.
  shift
  # Run exact command line given after "--run" in this environment.
  exec "$@"
else
  # Run real itkwish executable in this environment.
  exec "${ITKWISH_LIBDIR}/itkwish" "$@"
fi
