#include <vnl/vnl_vector_fixed.h>
#include <vnl/vnl_vector_fixed.txx>

VNL_VECTOR_FIXED_INSTANTIATE(double,1);
VNL_VECTOR_FIXED_INSTANTIATE(double,2);
VNL_VECTOR_FIXED_INSTANTIATE(double,3);
VNL_VECTOR_FIXED_INSTANTIATE(double,4);
VNL_VECTOR_FIXED_INSTANTIATE(double,6);
VNL_NON_TEMPLATE_FIXED_CROSS_3D_INSTANTIATE(double);

VNL_VECTOR_FIXED_INSTANTIATE(float,1);
VNL_VECTOR_FIXED_INSTANTIATE(float,2);
VNL_VECTOR_FIXED_INSTANTIATE(float,3);
VNL_VECTOR_FIXED_INSTANTIATE(float,4);
VNL_NON_TEMPLATE_FIXED_CROSS_3D_INSTANTIATE(float);

VNL_VECTOR_FIXED_INSTANTIATE(int,1);
VNL_VECTOR_FIXED_INSTANTIATE(int,2);
VNL_VECTOR_FIXED_INSTANTIATE(int,3);
VNL_VECTOR_FIXED_INSTANTIATE(int,4);
VNL_NON_TEMPLATE_FIXED_CROSS_3D_INSTANTIATE(int);
