IF (USE_SCSL)

SET(SCSL_INC_SEARCHPATH
	/usr/include
)

FIND_PATH(SCSL_INCLUDE_PATH scsl_fft.h ${SCSL_INC_SEARCHPATH})

IF(SCSL_INCLUDE_PATH)
	SET(SCSL_INCLUDE ${SCSL_INCLUDE_PATH})
ENDIF (SCSL_INCLUDE_PATH)
MESSAGE(STATUS "INCLUDE PATH " ${SCSL_INCLUDE_PATH} )

FIND_LIBRARY(SCSL_LIB_PATH scs /usr/lib32 /usr/lib /usr/local/lib )

IF(SCSL_LIB_PATH)
        GET_FILENAME_COMPONENT(SCSL_LIB ${SCSL_LIB_PATH} PATH)
ENDIF(SCSL_LIB_PATH)

MESSAGE(STATUS "LIB PATH " ${SCSL_LIB} )


IF(SCSL_INCLUDE)
	IF(SCSL_LIB)
		SET(SCSL_FOUND 1)
	ENDIF (SCSL_LIB)
ENDIF(SCSL_INCLUDE)

IF(SCSL_FOUND)
	INCLUDE_DIRECTORIES( ${SCSL_INCLUDE})
	LINK_DIRECTORIES( ${SCSL_LIB} )
        ADD_DEFINITIONS(-DUSE_SCSL)
ENDIF (SCSL_FOUND)

MARK_AS_ADVANCED(SCSL_INCLUDE_PATH SCSL_LIB_PATH)

ENDIF (USE_SCSL)