#
# Figure out how the compiler prefers to declare templated functions as friends
# of a templated class.
#
SET(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT)
TRY_COMPILE(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_NULL_STRING
      ${ITK_BINARY_DIR}/CMakeTmp
      ${ITK_SOURCE_DIR}/CMake/itkTestFriendTemplatedFunction.cxx
      COMPILE_DEFINITIONS -DTRY_COMPILE_FRIEND_WITH_NULL_TEMPLATE_STRING
      OUTPUT_VARIABLE ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT
      )
IF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_NULL_STRING)
IF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
IF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
SET(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_NULL_STRING CACHE INTERNAL FALSE)
ENDIF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
ENDIF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
ENDIF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_NULL_STRING)

TRY_COMPILE(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_EMPTY_BRACKETS
      ${ITK_BINARY_DIR}/CMakeTmp
      ${ITK_SOURCE_DIR}/CMake/itkTestFriendTemplatedFunction.cxx
      COMPILE_DEFINITIONS -DTRY_COMPILE_FRIEND_WITH_EMPTY_TEMPLATE_BRACKETS
      OUTPUT_VARIABLE ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT
      )
IF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_EMPTY_BRACKETS)
IF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
IF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
SET(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_EMPTY_BRACKETS CACHE INTERNAL FALSE)
ENDIF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
ENDIF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
ENDIF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_EMPTY_BRACKETS)

TRY_COMPILE(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_TEMPLATE_ARGUMENTS
      ${ITK_BINARY_DIR}/CMakeTmp
      ${ITK_SOURCE_DIR}/CMake/itkTestFriendTemplatedFunction.cxx
      COMPILE_DEFINITIONS -DTRY_COMPILE_FRIEND_WITH_TEMPLATE_ARGUMENTS
      OUTPUT_VARIABLE ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT
      )
IF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_TEMPLATE_ARGUMENTS)
IF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
IF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
SET(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_TEMPLATE_ARGUMENTS CACHE INTERNAL FALSE)
ENDIF(NOT ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES " 0 [Ww]arning")
ENDIF(ITK_TEMPLATE_FRIEND_FUNCTION_TEST_OUTPUT MATCHES "[Ww]arning")
ENDIF(ITK_SUPPORTS_TEMPLATED_FRIEND_FUNCTION_WITH_TEMPLATE_ARGUMENTS)


