#!/bin/sh
echo 'Please initialize your local Git hooks.
Paste the following commands into a shell:

 cd "'$(pwd)'/.git/hooks"
 git init
 git pull .. remotes/origin/hooks
 cd ../..

See http://www.itk.org/Wiki/Git/Hooks for more details.'
exit 1
