#include <vnl/vnl_matrix_fixed_ref.hxx>
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,1,1);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,2,2);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,2,3);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,3,2);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,3,3);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,3,4);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,3,12);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,4,3);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,4,4);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,5,5);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,6,6);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,7,7);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,8,8);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,9,9);
VNL_MATRIX_FIXED_REF_INSTANTIATE(float,10,10);
