#include <vnl/vnl_complex.h>
#include <vnl/vnl_vector_fixed.hxx>
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  1);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  2);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  3);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  4);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  5);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>,  9);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>, 16);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<double>, 25);
