#include <vnl/vnl_matrix_fixed.hxx>
VNL_MATRIX_FIXED_INSTANTIATE(int,1,1);
VNL_MATRIX_FIXED_INSTANTIATE(int,2,2);
VNL_MATRIX_FIXED_INSTANTIATE(int,2,8);
VNL_MATRIX_FIXED_INSTANTIATE(int,3,4);
VNL_MATRIX_FIXED_INSTANTIATE(int,4,4);
VNL_MATRIX_FIXED_INSTANTIATE(int,8,2);
