#include <vnl/vnl_complex.h>
#include <vnl/vnl_vector_fixed.hxx>
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  1);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  2);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  3);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  4);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  5);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>,  9);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>, 16);
VNL_VECTOR_FIXED_INSTANTIATE(std::complex<float>, 25);
