MACRO(ADD_JAVA_TYPEMAP simple_name cpp_name swig_name template_params)
  # write me
ENDMACRO(ADD_JAVA_TYPEMAP)


MACRO(JAVA_SUPPORT_CONFIGURE_FILES)
  # write me
ENDMACRO(JAVA_SUPPORT_CONFIGURE_FILES)



