WRAP_CLASS("itk::FastMarchingExtensionImageFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t ${WRAP_ITK_REAL})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_UC}1${ITKM_I${t}${d}}" "${ITKT_I${t}${d}}, ${ITKT_UC}, 1, ${ITKT_I${t}${d}}")
    endforeach(t)
  endforeach(d)
END_WRAP_CLASS()
