WRAP_CLASS("itk::BinaryStatisticsKeepNObjectsImageFilter" POINTER)
  foreach(d ${WRAP_ITK_DIMS})
    foreach(t2 ${WRAP_ITK_SCALAR})
      foreach(t1 ${WRAP_ITK_USIGN_INT})
        WRAP_TEMPLATE("${ITKM_I${t1}${d}}${ITKM_I${t2}${d}}"  "${ITKT_I${t1}${d}},${ITKT_I${t2}${d}}")
      endforeach(t1)
    endforeach(t2)
  endforeach(d)
END_WRAP_CLASS()
