/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    itkReviewHeaderTest.cxx
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) Insight Software Consortium. All rights reserved.
  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>
#include <cstdlib>
// This file has been generated by BuildHeaderTest.tcl
// Test to include each header file for Insight

#include "itkBinaryMorphologicalClosingImageFilter.txx"
#include "itkBinaryMorphologicalOpeningImageFilter.txx"
#include "itkConformalFlatteningMeshFilter.txx"
#include "itkContourExtractor2DImageFilter.txx"
#include "itkFlatStructuringElement.txx"
#include "itkGeometricalQuadEdge.txx"
#include "itkImageToPathFilter.txx"
#include "itkLabelOverlayFunctor.h"
#include "itkLabelOverlayImageFilter.txx"
#include "itkLabelToRGBFunctor.h"
#include "itkLabelToRGBImageFilter.txx"
#include "itkMatlabTransformIO.h"
#include "itkMatlabTransformIOFactory.h"
#include "itkMorphologicalWatershedFromMarkersImageFilter.txx"
#include "itkMorphologicalWatershedImageFilter.txx"
#include "itkNeuralNetworkFileReader.txx"
#include "itkNeuralNetworkFileWriter.txx"
#include "itkQuadEdge.h"
#include "itkQuadEdgeCellTraitsInfo.h"
#include "itkQuadEdgeMesh.txx"
#include "itkQuadEdgeMeshBaseIterator.h"
#include "itkQuadEdgeMeshBoundaryEdgesMeshFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorCreateCenterVertexFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorDeleteCenterVertexFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorFlipEdgeFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorJoinFacetFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorJoinVertexFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorSplitEdgeFunction.h"
#include "itkQuadEdgeMeshEulerOperatorSplitFacetFunction.txx"
#include "itkQuadEdgeMeshEulerOperatorSplitVertexFunction.txx"
#include "itkQuadEdgeMeshFrontIterator.txx"
#include "itkQuadEdgeMeshFunctionBase.h"
#include "itkQuadEdgeMeshLineCell.txx"
#include "itkQuadEdgeMeshMacro.h"
#include "itkQuadEdgeMeshPoint.txx"
#include "itkQuadEdgeMeshPolygonCell.txx"
#include "itkQuadEdgeMeshToQuadEdgeMeshFilter.txx"
#include "itkQuadEdgeMeshTopologyChecker.txx"
#include "itkQuadEdgeMeshTraits.h"
#include "itkQuadEdgeMeshZipMeshFunction.txx"
#include "itkRegionalMaximaImageFilter.txx"
#include "itkRegionalMinimaImageFilter.txx"
#include "itkTransformFileReaderWithFactory.h"
#include "itkTransformFileWriterWithFactory.h"
#include "itkTransformIOBase.h"
#include "itkTransformIOFactory.h"
#include "itkTxtTransformIO.h"
#include "itkTxtTransformIOFactory.h"
#include "itkVTKPolyDataReader.txx"
#include "itkVTKPolyDataWriter.txx"
#include "itkValuedRegionalExtremaImageFilter.txx"
#include "itkValuedRegionalMaximaImageFilter.h"
#include "itkValuedRegionalMinimaImageFilter.h"

#include "itkBoxImageFilter.h"

int main ( int , char * [] )
{
  
  return EXIT_SUCCESS;
}
