name: Apply clang-format to PR

on:
  pull_request:
    types: [labeled]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: InsightSoftwareConsortium/ITKApplyClangFormatAction@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
