name: Label PRs

on:
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@v0.8
      env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
